### ISSUE TITLE
Add forking terms to Glossary

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#1001]
- Fork
- Hard Fork
- Soft Fork

**Comment by s-ben** [comment]
Can take a crack at these unless someone else wants them.

**Comment by jholdstock** [comment]
It might be sensible to include two definitions of fork - source code fork and chain fork.

**Comment by s-ben** [comment]
Right. Would also be a good opportunity to clear up confusion about Decred being a "fork" of Bitcoin, as CMC insists on keeping in their [description](https://coinmarketcap.com/currencies/decred/).
