### ISSUE TITLE
Wikipedia.org Decred page

### ISSUE THREAD

**Issue by animedow** [decred/dcrdocs#101]
At the moment there is no Decred entry on wikipedia.
As a low level entry point to Decred this can be very useful.

**Comment by jcvernaleo** [comment]
Agreed.  For starters, it should be a very simple page with NO content that was copied and pasted from other docs of ours.
Another useful thing would be to add links to this page from other wikipedia pages (lists of alt-coins, projects using go, things like that).

**Comment by animedow** [comment]
I'll start working on this next.
I'm collecting news links for reference material. If anyone has any not listed here, please add them.

**Comment by noahpierau** [comment]
Maybe a good reference project on Wikipedia is [https://en.wikipedia.org/wiki/Ubiq](https://en.wikipedia.org/wiki/Ubiq)

We could also use the 'cryptocurrency' category. That might provide the context to be regarded as legit. I propose we will use the 'Other proof-of-work' subcategory. In time we could create a whole new subcategory calling it 'hybrid proof-of-work' or something along those lines. 

Other link to reference:

Decred the top performing currency from Q1 2017
[http://www.coindesk.com/800-growth-q1s-top-performing-cryptocurrencies-posted-big-gains/](http://www.coindesk.com/800-growth-q1s-top-performing-cryptocurrencies-posted-big-gains/
)

**Comment by nickboariu** [comment]
Wikipedia is published

**Comment by jholdstock** [comment]
@dajohi  I think we can probably close this off - [the wiki page exists now](https://en.wikipedia.org/wiki/Decred) and it seems to use most of the sources listed above.

**Comment by xaur** [comment]
Decred's Wikipedia page was voted down and removed by suspicious people. Follow here: https://github.com/decredcommunity/issues/issues/79
