### ISSUE TITLE
Support Page

### ISSUE THREAD

**Issue by gratefulcheddar** [decred/dcrdocs#103]
Add a support page - "Where To Get Additional Help". Show the directory that coin_artist made in Slack, add instructions for getting an invite to Slack, link to forums, IRC, etc,...

**Comment by jcvernaleo** [comment]
I believe this was done in #107 @gratefulcheddar was anything missing from that which you wanted or can I close this?

**Comment by jcvernaleo** [comment]
Confirmed on slack that this is done so closing.
