### ISSUE TITLE
CoinShuffle++

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#1031]
A new page for CoinShuffle++ should be added to the docs. #986 already added a "Privacy" submenu , so this seems to be the natural home for such a page.

Material we should cover:

- What is CoinShuffle++ and how does it work?
- How do I use CSPP?
- Why does it use a centralized server?
- Benefits and limitations

Reference material:
- [DiceMix Light](https://github.com/ElementsProject/dicemix/blob/master/doc/protocol.md)
- [CoinShuffle](https://eprint.iacr.org/2016/824.pdf)
- https://cspp.decred.org/
- https://github.com/decred/cspp
- Blog posts: [#1](https://blog.decred.org/2019/08/21/Surveying-the-Privacy-Landscape/) [#2](https://blog.decred.org/2019/08/28/Iterating-Privacy/)

**Comment by pLabarta** [comment]
I'm working on a first draft!
