### ISSUE TITLE
Update How to Vote page to make it generic

### ISSUE THREAD

**Issue by s-ben** [decred/dcrdocs#1050]
In the [How to Vote page](https://docs.decred.org/governance/consensus-rule-voting/how-to-vote/) detailing voting on consensus changes, we reference "vote version 5". However, this will become out of date with subsequent votes. We should make the text generic so we don't have to update it after every vote (which we'll invariably forget to do).

**Comment by davecgh** [comment]
Just to note that it's already out of date.  The current vote version is 7 and the current agenda/vote id is `headercommitments`.
