### ISSUE TITLE
Fix broken image How to Vote page

### ISSUE THREAD

**Issue by s-ben** [decred/dcrdocs#1051]
In the [How to Vote page](https://docs.decred.org/governance/consensus-rule-voting/how-to-vote/), an image is 404'ing. Fix image and, if needed, change the text introducing it (it may be out of date?).

**Comment by jholdstock** [comment]
Interesting that this image has been problematic in the past: #617

**Comment by jholdstock** [comment]
I removed the image accidentally in #834

I think this is a recurrent problem because the image is in the `/img/decrediton` directory, but its not actually used in the decrediton pages. I'm going to move it
