### ISSUE TITLE
Contributing: link to personal stories

### ISSUE THREAD

**Issue by xaur** [decred/dcrdocs#1054]
I've just listened Decred in Depth with @jholdstock and realized that his story of getting involved with Decred is a useful onboarding material.

What do you think about adding a bullet list of personal stories to the [contributing](https://docs.decred.org/contributing/overview/) page? e.g.

> For a more personal perspective, check these stories where some Decred contributors share their experience of getting involved in Decred:
>
> - Working for the Decred DAO by richardred ([medium](https://medium.com/@richardred/working-for-the-decred-dae-a9cfb17686fa#5a3c))
> - I Dump My Coins on You by s_ben ([medium](https://medium.com/@seth.benton/i-dump-coins-on-you-ee6db4331e18))
> - Working for the Decred DAO + Development - an episode of Decred in Depth podcast with jholdstock ([youtube](https://www.youtube.com/watch?v=A-zcLGSYxbA), [libsyn](https://decredindepth.libsyn.com/ep-6-working-for-the-dcr-dao-development-with-jamie-holdstock))

**Comment by s-ben** [comment]
I like this idea. While it's generally advisable to keep marketing material out of the technical documentation, in this case, there is very little "official" general information available about becoming/being a contractor. Having personal stories adds a ton of useful information to someone looking into contributing. And I think i all three of these examples, we're being pretty real, not just shilling.
