### ISSUE TITLE
Change name of Reading List to Decreducation

### ISSUE THREAD

**Issue by Dustorf** [decred/dcrdocs#1056]
Reading List sounds boring and tedious. Decreducation is fun. I believe far more people will spend time and read through the media if it's called something more approachable and less academic.
@jholdstock

**Comment by Dustorf** [comment]
It's also not simply a reading list. There are many podcasts and videos as well.

**Comment by s-ben** [comment]
+1 for something more expressive and enticing. Not sure about Decreducation though. A newcomer skimming the docs for education materials may not get it. Dat name...Maybe something like 'Educational Resources', 'Decred Media', 'Further Learning', etc.?

**Comment by Dustorf** [comment]
Articles & Media
Educational Resources
The Rabbit Hole

**Comment by s-ben** [comment]
All those are good....I'd say in the order you list them. Articles and media makes most sense to me.

**Comment by Dustorf** [comment]
Let's change it to "Articles & Media"

It's accurate and doesn't shove homework in people's faces.
