### ISSUE TITLE
Golden Path discussion

### ISSUE THREAD

**Issue by gratefulcheddar** [decred/dcrdocs#106]
Need to agree on a "map" for our Golden Path. How does everyone interpret the words "Golden Path"?

**Comment by gratefulcheddar** [comment]
In my head I see something like what I've done in #105. Where the Golden Path greets them and sends them on a journey of learning how to use the software to meet their most basic cryptocurrency needs (wallet setup, sending/receiving, staking, mining). 

My pull request has Golden Path Intro -> Operating System Compatibility/Differences/App Descriptions -> Download and Install.

From Download and Install, they can take the Paymetheus Path (Paymetheus Setup -> Usage) or the CLI Path (Startup Options Information -> dcrd Setup -> dcrwallet Setup -> dcrctl Basics). 

Before #105, the Paymetheus Path was the same, and dcrd Setup, dcrwallet Setup, dcrctl Basics were combined in a single page, but with 3 different versions - Windows, Mac, and Linux. I abstracted the differences into Operating System#Differences, and went with OS-agnostic guides to aid in sharing.

Then, both paths lead to Obtaining DCR and the PoS Guide. 

Also all of the guides in the Path that I've touched, I've put a list of prerequisites near the top of the page.

**Comment by fai04d** [comment]
I'm open to changes, but it needs to be very simple. There should not be too many deviations.  The nav panel is always there for people who want to wander, but the path needs to be *very* hand-holdy. Remember, this is to capture people who know almost nothing about crypto currency, maybe even bitcoin, and probably don't even know what a cli is let alone how to use one.

The aim is to capture those who don't know where to begin. To give them a path through the docs to get them started and not overwhelm them with information.

Quite frankly, the purpose of the path is to tell them what to do. Not to give them options. They're too new for that. They don't care about differences, they just want something easy to get them started.

Further, I CANNOT overstate the adversity many people have to the command line. I want the GP to guide new users towards the GUI options whilst keeping the CLI open for those who know how to use it. Just reading Slack tonight, I've seen two people who would rather wait for GUI tools than use the CLI.

I don't have any problems with changing the path, just don't forget who it's intended for!

**Comment by gratefulcheddar** [comment]
So focus on Paymetheus and Decrediton for the Golden Path. I can agree with that.

What you say about GUI vs. CLI is true, but I also think a Beginner CLI Path is very valuable. 

So for this #105, I can put it back to how it was, and the CLI mini-path I created can still exist in the sidebar navigation.

**Comment by gratefulcheddar** [comment]
Think we should leave this open for more discussion

**Comment by animedow** [comment]
I agree with fai04d on emphasizing the GUI over CLI in the golden path. People who know how to use CLI will figure it out. Although this doesn't mean that the docs don't have to be clear for CLI. A good place for this might be the technical FAQ sections. As in, make sure those cover all the bases that aren't touched upon in the quick and dirty CLI getting started page.

Also, do we have to call it 'The Golden Path' ?
To be honest, it sounds a bit corny to me. Just have it read 'Beginner's Guide' should be enough.

**Comment by jcvernaleo** [comment]
@animedow I had never heard the term 'Golden Path' before now either.  I'd be happier with 'Beginner's Guide' too but I'd like to hear from the people who initially called it that.

**Comment by fai04d** [comment]
I just liked the imagery. You know, follow the yellow brick road, etc. I was actually going to just call it 'The Golden Path' and not have 'Beginners guide' in there at all since it's more a walk though a collection of guides as opposed to a guide itself, hence the 'path' term. I added the rest as I thought the significance might be lost on other cultures where those other terms may not mean anything.

At any rate, I don't particularly care what it's called. The landing page should do a job of explaining it, so the name doesn't need to do that.

**Comment by animedow** [comment]
Path is a nice analogy for to guide, but from the perspective of a beginner might it not be confusing?
Just from my personal perspective, when I start something new I'm looking for terms like "Getting started", "Start here", "Guide", "Download and install".

At the moment the term is used only once on the landing page of the 'Getting Started' section. Which makes it seem that it's used for show only and not actually be useful. In case we keep it, though, the guides are 'on' the path, not 'in' (as it reads now). As you walk on a path, not in it.

But then again, I don't have an artistic bone in my body. So something like this could be nice and flowery for new people and hook them.

**Comment by jcvernaleo** [comment]
I think we kind of decided how to go with #105 so I'm going to close this.  If I missed something, feel free to reopen (or open a new one).
