### ISSUE TITLE
Rename Inflation page

### ISSUE THREAD

**Issue by xaur** [decred/dcrdocs#1074]
Term ["inflation"](https://en.wikipedia.org/wiki/Inflation) is ambiguous and often refers to "prices inflation". Our [Inflation page](https://docs.decred.org/advanced/inflation/) has nothing to do with prices but instead is talking about "inflation of the monetary supply".

There are more specific terms for the page: Emission, Emission schedule, [Monetary inflation](https://en.wikipedia.org/wiki/Monetary_inflation), Issuance (schedule), Creation of (money|currency), [Money supply](https://en.wikipedia.org/wiki/Money_supply), etc. I would pick Emission.

**Comment by pLabarta** [comment]
I would go with "Issuance", mainly because it involves the distribution of things and belongs to the Law/Economy world. "Emission" is also used to refer to gases when talking about the environment.

Issuance of DCR...

**Comment by s-ben** [comment]
When I hear "Emission", it brings to mind debates around PoW coins without a fixed cap (e.g. Monero). Perhaps Issuance is better?

**Comment by RichardRed0x** [comment]
Issuance and issuance schedule for me.

**Comment by Dustorf** [comment]
I like @RichardRed0x 's suggestion of Issuance and Issuance Schedule. Better than helicopter drops.
