### ISSUE TITLE
warn about seed re-use/sharing

### ISSUE THREAD

**Issue by jolan** [decred/dcrdocs#108]
Numerous support issues have been related to plugging the same seed into multiple wallets, web wallet, etc. and using them concurrently.

This is unsupported and causes problems when the wallets fail to receive/see all transactions/addresses.

Should strongly recommend "new wallet, new seed".

**Comment by jholdstock** [comment]
I'll take this one.

**Comment by jcvernaleo** [comment]
@jholdstock for some unknown reason it still will not let me assign an issue to you but it is noted, this one is all yours.
