### ISSUE TITLE
Add a line explaining how to restore accounts 

### ISSUE THREAD

**Issue by zubairzia0** [decred/dcrdocs#1086]
When a wallet is restored from a backup in decrediton, only the default account is initially restored. If there were multiple accounts they will need to be restored by recreating accounts and then rescanning. I think we can add a line or two explaining how to do that. 

https://docs.decred.org/wallets/decrediton/decrediton-setup/#restore-existing-wallet

**Comment by pLabarta** [comment]
Just tested it with Decrediton v1.5.1 and the other accounts were generated without needing to recreate them. The have default names like "account-1", but that's all.

**Comment by zubairzia0** [comment]
Ah ok that's good then. Will close
