### ISSUE TITLE
verifying binaries key import

### ISSUE THREAD

**Issue by raedah** [decred/dcrdocs#1088]
gpg keyserver command has a copy box next to it. The copy box is copying the cmd and the output of the cmd that is shown in the docs. Expected behavior is for it to copy just the command that the user needs to run.

Currently, the keyserver seems to be down. What is the fallback method / location to obtain the key needed?

**Comment by jholdstock** [comment]
The behaviour of the copy button is built into the mkdocs theme ([mkdocs-material](https://squidfunk.github.io/mkdocs-material/)) and not something we can easily configure or override. I would be reluctant to start hacking on the theme just to change this.

If https://pgp.key-server.io goes down, a valid workaround is to use https://keys.openpgp.org instead, or any other publicly available keyserver which the reader trusts. This could be added to the docs.
