### ISSUE TITLE
Update SPV

### ISSUE THREAD

**Issue by degeri** [decred/dcrdocs#1099]
SPV page https://docs.decred.org/wallets/spv/ needs to be updated to reflect the latest consensus changes https://proposals.decred.org/proposals/0a1ff846ec271184ea4e3a921a3ccd8d478f69948b984445ee1852f272d54c58

**Comment by jholdstock** [comment]
The hard fork has been done, but the false-positive scenario is still a possibility because the wallet changes are not made yet. Likely will be in 1.6 release
