### ISSUE TITLE
Add command for CLI password change with promptsecret

### ISSUE THREAD

**Issue by Arriu** [decred/dcrdocs#1108]
This command, taught to me by dave, allows you to change the password in the CLI without having to type it out visibly on the screen. ALERT!: It does not ask for verification of the new password, so one needs to take extra care that the new password is entered correctly on the first go. Probably best to make a backup of the wallet file beforehand just in case a typo sneaks in.

./promptsecret -n 2 | ./dcrctl --wallet walletpassphrasechange - -

Please close in case this is alrdy in the docs. I haven't been able to find it if it is.

**Comment by dezryth** [comment]
This executable is referenced here: https://docs.decred.org/wallets/cli/dcrctl-basics/#unlocking-your-wallet 
I believe this issue can be closed.
