### ISSUE TITLE
cannot send any transaction anymore

### ISSUE THREAD

**Issue by odoo-mvds** [decred/dcrdocs#1113]
Hello,

reinstalled several times already.
Tried several computers. Even mobile.

I'm unable to transfer decred to another account....

![image](https://user-images.githubusercontent.com/59664044/88664040-bf5ac180-d0dc-11ea-9c61-5bf347a2e31d.png)

**Comment by jholdstock** [comment]
Hi there, sorry to hear about your problem. This repository is not the correct place to come for wallet support, I suggest you visit https://decred.org/community and join the support channel of your favoured chat platform.

**Comment by odoo-mvds** [comment]
Hi,
contacted support but they don't know really how to solve it. 
I see this error in you mac os client:
"is not standard: transaction size of 160164 is larger than max allowed size of 100000"
