### ISSUE TITLE
"decred: where it all began" dead link

### ISSUE THREAD

**Issue by mmikeww** [decred/dcrdocs#1114]
first link on this page:
https://docs.decred.org/getting-started/articles-and-media/

**Comment by jholdstock** [comment]
Thanks for reporting this. We are trying to get in touch with the operator of the site.

For the meantime, a version of the article is available at https://archive.is/1nnxq

**Comment by jholdstock** [comment]
Link has been updated to https://medium.com/decred/decred-where-did-it-all-begin-6d63b5c62fc4

Thanks again
