### ISSUE TITLE
VSP shutdown guidelines

### ISSUE THREAD

**Issue by xaur** [decred/dcrdocs#1139]
This [tweet](https://twitter.com/staked_us/status/1329173484598124546) by Staked on Nov 18 announced the closure of their VSP and asked to migrate by Dec 1. As of Dec 8 they still have [31 live ticket](https://decred.staked.us/stats). I'm uncertain if they were serious since their site still lists DCR but in any case, these events suggest they are not aware of a graceful way to shut down a VSP (because tickets may stay live for a long time).

It would be good to have guidelines for shutting down a VSP (and soon vspd) written in a well-known place, like [Operating a VSP](https://docs.decred.org/advanced/operating-a-vsp/) or a separate page, and communicated as part of service operator briefing (you need to have at least 3 servers, and a voted ticket, oh and please read this doc too).

I would start from a recommended timeline like

- announce the closure ~6 months ahead
- put a visible notice on your site
- stop accepting new registrations
- email your users
- tweet on Twitter and ask @decredproject to retweet
- wait until all tickets vote and there are no live tickets

If there is any way to migrate live tickets we should inform about that too.

vspd instructions will differ and I hope a graceful shutdown process is supported at the protocol level (e.g. it can reject new ticket registrations with some status message). Ideally we would want the shutdown process to be supported in Decrediton too with UI clues how to react to it.

The focus of this process should be to prevent as much missed tickets as possible.

**Comment by jholdstock** [comment]
@degeri  can you please share the doc you put together for this?

**Comment by degeri** [comment]
https://gist.github.com/degeri/a489b458b1a850ff378914f464f158c6

**Comment by xaur** [comment]
Since this will likely update Operating a VSP page anyway, please also add this from https://github.com/decred/vspd/issues/253

> Part of the social contract when you are a listed VSP operator is staying contactable for important updates or messages

**Comment by jholdstock** [comment]
I'm going to close this because I've reviewed everything above and none of it is really relevant to vspd. dcrstakepool was complicated to shut down cleanly because there was no formal way of preventing users from registering new tickets. The process for vspd however is far more self-explanatory (set `vspclosed=1` in config, optionally notify the community). Having a document for this feels like unnecessary overkill.
