### ISSUE TITLE
Issuance: projection table confuses by showing DCR for only 1 vote

### ISSUE THREAD

**Issue by xaur** [decred/dcrdocs#1143]
The table at the end of the [Issuance](https://docs.decred.org/advanced/issuance/) page shows DCR for 1 PoS vote and not 5. This is confusing because the PoW+PoS+Treasury columns do not add up to the Block reward column. And also because the Total DCR supply column is incremented with the assumption that each block includes all 5 votes.

**Comment by dezryth** [comment]
I will work on this one by adding a column to show total POS reward from each block. @xaur

**Comment by xaur** [comment]
@dezryth that will resolve this issue, although I wonder if a column for 1 vote reward is necessary.

**Comment by dezryth** [comment]
I think especially as more newbies look into staking they will be interested in the reward per ticket but happy to remove it completely if you think it's necessary. If not, merged PR #1149 resolves this issue.

**Comment by xaur** [comment]
I'll wait until the change is deployed to see how more columns look and whether the table becomes too heavy. Let's keep this issue open for a while, and maybe someone else can comment too.

**Comment by xaur** [comment]
Ok the new column looks good and the table didn't get too fat. Also, re-reading this convo now

> as more newbies look into staking they will be interested in the reward per ticket

makes a lot of sense, so let's keep it. Thanks!
