### ISSUE TITLE
How To Fix Paymetheus Balance

### ISSUE THREAD

**Issue by gratefulcheddar** [decred/dcrdocs#119]
If someone wants to make these instructions look pretty before the next release, go for it

* open two powershell windows
* in both of them cd to $env:programfiles/decred/paymetheus
* open explorer to %localappdata%/decred/paymetheus and remove the mainnet directory
* now in one of the consoles run ./dcrd -u you -P sekrit
* in the other window run ./dcrwallet --appdata=$env:localappdata/decred/paymetheus --create
* then follow the prompts and import your seed
* run ./dcrwallet -u you -P sekrit --appdata=$env:localappdata/decred/paymetheus
* open a third powershell window and cd to that same directory ($env:programfiles/decred/paymetheus)
* in the third window run ./dcrctl -u you -P sekrit --wallet -c $env:localappdata/decred/paymetheus/rpc.cert getbalance
* press control-C in the wallet console and in the dcrd console
* remove the rpc.cert and rpc.key files from %localappdata%/decred/paymetheus
* now click decred on the start menu

**Comment by fai04d** [comment]
Thanks, I'm doing an errors FAQ, I'll add it in there.
