### ISSUE TITLE
Update docs so infomation corresponds to the changes implemented in DCP0009 and DCP0010.

### ISSUE THREAD

**Issue by Arriu** [decred/dcrdocs#1194]
Because of the changes sever pages like https://docs.decred.org/advanced/issuance/ are no longer accurate. I'll go over the docs in the next couple of days and 'll make a list of pages that need to be altered. I'll add that to this issue when its done.

**Comment by xaur** [comment]
That would be great!

The v1.7 release got an unfortunate combo of two events - it contained an economical change with huge impact on mining  _and_ was done without thoroughly updating all pages to reflect that. Some miners rightfully [complain](https://www.reddit.com/r/decred/comments/v6d0lw/luxor_shutdown_their_dcr_mining_pool/ibhoydn/) that the PoW reward reduction was not mentioned on the [Issuance](https://docs.decred.org/advanced/issuance/) page.

**Comment by jholdstock** [comment]
Issuance page updated in #1198. Is there anything else to do?

**Comment by Arriu** [comment]
1) home page: docs.decred.org: there a table here with incorrect stats, the text which follows also needs to be reworked

2) constitution: https://docs.decred.org/governance/decred-constitution/: ctrl + f "subsidy"

3) glossary: https://docs.decred.org/glossary/#hybrid-powpos: incorrect percentages

**Comment by noahpierau** [comment]
https://github.com/decred/dcrdocs/edit/master/docs/governance/decred-constitution.md 

this still needs an update. specifically these sections: 

_Stakeholder votes recorded in the blockchain are rewarded with 6% of each block subsidy, and each block can have up to 5 votes for a total of 30% of each block subsidy.

PoW receives 60% of each block subsidy, subject to the constraint that their subsidy scales linearly with the number of PoS votes included, e.g. including 3 of 5 votes reduces PoW subsidy to 60% of the maximum._
