### ISSUE TITLE
Update project history timeline

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#1208]
#1206 copied the history page from decred.org verbatim. It could use some updates - most noticeably the timeline doesn't include any recent milestones. 

Some examples - DEX launch, DEX upgrades, mixing launch, quantum secure mixing, subsidy split change, decentralized treasury

**Comment by xaur** [comment]
FYI lurkers project history is now located at https://docs.decred.org/getting-started/project-history/

**Comment by jholdstock** [comment]
Done in #1212 and #1232
