### ISSUE TITLE
“Integration Partnership proposal”

### ISSUE THREAD

**Issue by Raihanyosofi** [decred/dcrdocs#1211]
“Integration Partnership proposal”

Verseshoe, we design fabulous animated shoe collections in the NFT space and the real world. Our goal is to allow our community to receive unlimited benefits from these mind-blowing shoes. The brand provides the holders of these fantasy shoes to bring their Verse-shoe NFTs to life and wear them. The only way to get one of these golden shoes is to own one NFT from our first drop, “VS Character” ( Coming soon).  The profits from this collection go to charity. We don’t limit the brand only there; many upcoming Metaverse games (where you play to earn) and events are yet to come. 
Thanks 
We are better together! Verseshoe brand is now open for partnerships with other fashion brands, Coins, and NFT marketplaces. The brand recently started a collaboration with Chainlink. They have developed helpful tools to make the minting process more manageable and safer. 
	⁃	Do you also have tools and resources to help Verseshoe improve more?

      - Do you have tools to use & airdrop NFTs using your coins? 
We have over 10k NFTs that we want to airdrop to our community using any tool is available.

Or is there any integration partnership that fits us? Let us know!

What is your benefit? 
Integrating with Verseshoe not only your product’s value increases but also we drive our 300k community members to your company and do a free promotion & recommending your company.

We would be glad To hear from you! Contact the Verseshoe team via the platform of your choice:

https://linktr.ee/verseshoes

**Comment by jholdstock** [comment]
https://docs.decred.org/governance/politeia/overview/
