### ISSUE TITLE
HTML/Template: Remove individual headers from navigation

### ISSUE THREAD

**Issue by gratefulcheddar** [decred/dcrdocs#129]
Right now, the navigation menu/table of contents lists all the headers of the page currently loaded.

Small section in tpldcrdocs/toc.html that needs to be removed for this: the `{% if nav_item == page %}` block.

**Comment by jholdstock** [comment]
@jcvernaleo what's going on with this issue? Is this on hold until it has designer approval?

I would really like to see it implemented and as @gratefulcheddar points out, its a really quick simple change. I work with the change locally and it makes navigating the docs much more pleasant. When I visit the live site these days the ToC is a real pain in the ass.

**Comment by jcvernaleo** [comment]
Yeah, we're kind of sitting on design issues for the moment until we can talk with the designers (and with all of you docs contributers too, you folks get a say as well!) for what we should do about the docs.  We could keep hacking the current theme, or go with something that is closer to the designers themes for other parts.  But either way it has to be post release so outside of specific bug fixes, I'd like to hold off on any of the design issues.

**Comment by pvtwarren** [comment]
The design of the current navigation menu/table is very confusing. I've stared over 10 minutes at it and I still have trouble grapsing the logic.

**Comment by jholdstock** [comment]
This can finally be closed thanks to #419 :)

@dajohi

**Comment by jolan** [comment]
Closed via #419.
