### ISSUE TITLE
Make github more prominent

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrdocs#13]
There is a link to this github repo the docs website but we still might want to make it a little clearer that we want both issues and PRs on the docs repo and that the docs site is not just some static thing but something we want people to help improve.

That said I'm not sure how we can best point that out which is why I've put an issue here rather than just going and changing it and doing a PR myself.

**Comment by Dyrk** [comment]
Maybe add at the bottom of each article some text like:
```
If you found a mistake you can <a href="https://github.com/decred/dcrdocs/issues/new" target="_blank">open an issue</a> or <a href="https://github.com/decred/dcrdocs/compare" target="_blank">send a pull request</a> if you want to improve this article.
```

**Comment by jcvernaleo** [comment]
I kind of think this issue was taken care of enough by #20 from @jolan.  Github is now linked at the top of the page and in the footer (with direct links to issues and PRs there).

Did we want anything else or can I close this?

**Comment by jolan** [comment]
Yeah I meant to follow up and ask if we could close this after #20 went in. Please go ahead and close it.
