### ISSUE TITLE
Do we need "Overview" pages?

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#136]
In particular I am referring to:
- faq/overview.md
- advanced/overview.md

These pages don't seem to contain any unique information and they aren't particularly insightful. Example from the advanced overview: 

> **Block Header Specifications**
> This page describes the Decred block header.

Also because these pages are maintained manually and not automatically generated, they can easily fall out of date. This has already happened and caused PR #135 to be necessary.

mining/overview.md and research/overview.md are different because they do contain information which is not replicated elsewhere, so I guess these should stay.

**Comment by jholdstock** [comment]
I tried to apply the "question" label to this issue but it seems I don't have permission.

**Comment by jcvernaleo** [comment]
Not sure why it doesn't let you label an issue you opened but I set it for you.

**Comment by fai04d** [comment]
I say get rid of them. They basically just list what's already in the nav pane.

**Comment by jcvernaleo** [comment]
I don't think they add to anything.  Just acting as a 2nd index (and one that falls out of date) is not helpful.  The one in the mining section too should probably go (just make sure that if there was any content in them that you move it somewhere.
