### ISSUE TITLE
getting-started/overview.md isnt used

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#137]
getting-started/overview.md is in our repo but it is not included in mkdocs.yml which means it is not visible when browsing dcrdocs.

**Comment by gratefulcheddar** [comment]
I pulled it from mkdocs.yml when I did #105, felt like beginner-guide.md was an adequate replacement. Wanted to review it before deleting, but forgot. Kind of think the note at line 29 belongs on beginner-guide.md.

**Comment by fai04d** [comment]
So long as the information is elsewhere, nuke it.
