### ISSUE TITLE
Create a 'Media' page.

### ISSUE THREAD

**Issue by fai04d** [decred/dcrdocs#138]
I think we should have a place to record interviews, articles, etc about Decred. Would give us a central place to keep links and direct people.

**Comment by jcvernaleo** [comment]
I think a media page is a great idea, but I think it belongs more on the main web page https://github.com/decred/dcrweb than it does in the docs.  @jolan main page is more your area than mine, what do you think?

**Comment by fai04d** [comment]
Just want to  keep a log until we decide:
https://www.cryptocoinsnews.com/decred-benefits-bitcoin-impasse-joins-altcoins-rise/
https://www.investitin.com/decred-altcoin-review/

**Comment by jcvernaleo** [comment]
Adding the survey-results label to this since the survey asks for this (#238) even though this issue predates the survey.

**Comment by hashcrown** [comment]
I'm keeping an updated sheet with press coverage. When the media page gets built, you can use this as a resource https://docs.google.com/spreadsheets/d/10Vz4-t4G9xv9Lkle67OhcwWWTkK_NNNloDD81raeLKw/edit#gid=0

**Comment by jholdstock** [comment]
I agree with jcv above - dcrweb feels like a better place for this. There is already a placeholder for a "News" page, so I think we can close this. @jolan @dajohi

**Comment by jolan** [comment]
Agreed, closing.
