### ISSUE TITLE
Beginner-guide.md: Add details on which applications can be used for staking.

### ISSUE THREAD

**Issue by gratefulcheddar** [decred/dcrdocs#140]
Noticed a few people wondering which app to use for staking (split into pool and solo staking).

**Comment by jcvernaleo** [comment]
I think we cover that pretty well in the proof of stake page https://github.com/decred/dcrdocs/blob/db6e9f410af9570e9c56ebc7bfd8ad4b0ca31df7/docs/mining/proof-of-stake.md

Maybe we should just link to that rather than duplicate content.

**Comment by jholdstock** [comment]
I think we can close this @dajohi . The docs and the wallets have moved on since this was created and I dont think this is an issue any longer
