### ISSUE TITLE
Voting agenda states

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#147]
Detail the lifecycle of a voting agenda. Attached is a slack conversation from the #hardforkwebsite channel, it contains a lot of useful information from @davecgh.

[slack-29-03-2017-2221.txt](https://github.com/decred/dcrdocs/files/880456/slack-29-03-2017-2221.txt)

**Comment by jolan** [comment]
This seems pretty well covered by https://docs.decred.org/getting-started/user-guides/agenda-voting/
