### ISSUE TITLE
FAQ: How do I find my wallet seed after wallet has been created?

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#149]
Explain why seed is only output during wallet creation, why it is not stored anywhere, and the reasoning behind why you cannot access it on demand.

**Comment by jholdstock** [comment]
It seems that creating a wallet with  `--unsafemainnet` flag actually does save the seed. We may want to leave this undocumented because its not something we would recommend users do.

There is a `getseed` command but it returns "disabled" and this is intentional. 

We should recommend that if a seed has been lost but the wallet is still accessible, that a new wallet is created (seed should be saved obv) and the funds are sent to the new wallet.

**Comment by jcvernaleo** [comment]
@jrick do we still want ```--unsafemainnet``` in the wallet at all or do you think we should kill it?  If we kill it, ```getseed``` can go too.

**Comment by jcvernaleo** [comment]
@jholdstock getseed was put in very early in the dev to help with some of our early debugging.  If @jrick agrees I'd be happy with killing it completely.

**Comment by jholdstock** [comment]
Right so presumably if the unsafe flag is set, then getseed actually works and doesn't just return disabled. Got it - thanks

**Comment by jrick** [comment]
Sorry didn't see this earlier.  I am totally ok with removing getseed and that unsafemainnet garbage.

**Comment by jholdstock** [comment]
General consensus seems to be that there is little value in adding more info for this topic to dcrdocs so I'm closing this off.

jrick has raised removing the two dcrwallet params here: https://github.com/decred/dcrwallet/issues/653
