### ISSUE TITLE
Why is installation locked to a specific drive and folder?

### ISSUE THREAD

**Issue by zimmah** [decred/dcrdocs#153]
It makes no sense to limit installation to C:\program files specifically.  
Manually moving the program after installing will cause it to not even run at all.
Why?

**Comment by jcvernaleo** [comment]
@zimmah I'm not really sure which program you are referring to.  This repo is for the docs so it probably doesn't belong here to being with.  Do you mean the Paymetheus install?  If so, could you open the issue in https://github.com/decred/Paymetheus/issues that way the Paymetheus dev can respond.

**Comment by jcvernaleo** [comment]
This was moved to decred/Paymetheus#235 so closing.
