### ISSUE TITLE
Voing only wallet guide needed

### ISSUE THREAD

**Issue by fai04d** [decred/dcrdocs#158]
A walk through for a voting only wallet would be a good idea.

**Comment by gozart1** [comment]
An overview about what accounts are and how they work would be helpful as well.
In this section https://github.com/decred/dcrdocs/blob/master/docs/mining/proof-of-stake.md#-manual-purchasing-of-tickets it says:

> It is recommended to generate a new account when joining a stake pool. This is because accounts are hardened so in the case of a total stake pool failure/shutdown, it would be safe to give the private key to another stake pool as long as that account only does voting and nothing else.
 
It's unclear to me what is meant by `because accounts are hardened`.

**Comment by fai04d** [comment]
I think we were going to remove the bit about voting accounts weren't we? Dev comment?

**Comment by jcvernaleo** [comment]
@jrick you might be best to comment on if we should remove the voting account stuff.

**Comment by jolan** [comment]
@fai04d This is about adding a voting **wallet** not a voting **account**. Currently the underlying wallets that the Decrediton/Paymetheus GUIs talk to/use don't vote themselves so users are forced to use a stake pool. This would help facilitate GUI users to setup their own voting wallets for solo staking.

**Comment by fai04d** [comment]
Sorry, yes, I was commenting on @gozart1's message. That should probably be a separate issue.

It's not a bad idea, but currently the only way to do that is via the cli which a lot of gui users don't want to touch. However, we could put together a script that will download and install dcrinstall then set up an environment, configure dcrd and dcrwallet and run the whole lot.

**Comment by karamble** [comment]
We talked about an area for 'system hardening' in the documentation, i guess topics like hot/cold wallets, voting only wallets and verification of binary and sourcecode downloads would be fit in there.

**Comment by jcvernaleo** [comment]
I think this would make the most sense in the system hardening section as well.

**Comment by jcvernaleo** [comment]
Closing this since the #187 covers this better.
