### ISSUE TITLE
Decrediton needs documentation

### ISSUE THREAD

**Issue by fai04d** [decred/dcrdocs#159]
Given that new version will be released in a couple of weeks, we might leave it until then, but we need to get some docs on Decrediton in. Specifically, move or replicate the installation instructions here and note paths for files for trouble shooting.

We'll also need to do a PoS guide for it when that is available.

**Comment by jholdstock** [comment]
@dajohi I suggest closing this one. Decrediton docs have been fleshed out since this was created.
