### ISSUE TITLE
Finally kill wiki

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrdocs#170]
Not 100% a docs issue but better for tracking here than anywhere else.

We need to find and change any places where we link to the wiki on sites we control and either remove them or replace them with links to the docs.  When this issue is closed, @dajohi can archive and kill the wiki.  Might want to redirect the subdomain domain to docs.decred.org at that point.

- [x] bitcointalk post
- [X] main webpage
- [x] docs pages (there are some links)
- [X] twitter? - doesn't link to wiki
- [x] forum (not in posts obviously)
- [x] /r/decred
- [x] Terms and rules on forum points to legacy wiki
- [x] package readmes
- [x] links to verifying sigs in release and binary repos

If anyone finds any other links, please comment here and I'll add them to this list.  If you take care of one of them, also comment so I can check it off.

**Comment by jolan** [comment]
bitcointalk post is done.

**Comment by jcvernaleo** [comment]
And looks like the twitter doesn't link to it at all.

**Comment by jholdstock** [comment]
dcrdocs is covered by PR #171 above.

I think there is only one reddit post we need to look at and its here: https://www.reddit.com/r/decred/comments/3x8r5n/decred_an_overview/

I've taken a reasonably detailed look at the wiki and can't find anything which references the wiki unless I dig really far back into old posts. I don't think we have anything to worry about on the forum.

**Comment by jcvernaleo** [comment]
Not really worried about reddit posts (since we will just has all links go to the main doc page).  I just wanted to make sure we didn't link to the wiki on the sidbar or something like that on the subreddit.

**Comment by jcvernaleo** [comment]
I meant that last comment for both reddit and the forum (in case the main page of the forum or something linked to wiki, not posts).

**Comment by jcvernaleo** [comment]
Confirmed the reddit had nothing on the sidebar

**Comment by jcvernaleo** [comment]
Forum is fine too.

**Comment by jholdstock** [comment]
We missed one! 

The `Terms and Rules` link at the bottom of the forum front page points to this wiki page:
 https://wiki.decred.org/Rules

The obvious solution is to move this page to dcrdocs and update the forum config so it points to the new location. We could also adapt these rules to make them cover slack comms as well as forum comms. I haven't given the rules an in-depth review so they may not even need any updating.

**Comment by jcvernaleo** [comment]
I don't think I ever saw that page before.

Does it belong in the docs?  I'm a little uncertain.  Would love to hear opinions (or alternative homes to it since I can't think of anywhere else).  I just don't want docs to become a dumping ground for any text we don't know what to do with.

Regardless, I'm adding it to the checklist on top.  Good catch.

**Comment by jholdstock** [comment]
Was the close a mistake?

I was thinking the same about the rules, the natural place for it to go is in the forum itself. Can we embed it in there some how? We could even just make it a pinned post if there isn't a feature in xenforo for this

**Comment by jcvernaleo** [comment]
Damn it, yes, the close was a mistake.

**Comment by jcvernaleo** [comment]
In my defense, anyone could miss the big, bright green button that says 'comment' and hit the close one instead :)

**Comment by jcvernaleo** [comment]
@jolan probably knows more about what we could do on the forum than I do but I'd even be happy with the pinned post idea.

**Comment by jolan** [comment]
I would just drop it. It's some generic boilerplate/copy and paste.

 https://www.google.com/search?q=This+is+a+Civilized+Place+for+Public+Discussion+Please+treat+this+discussion+platform+with+the+same+respect

**Comment by jcvernaleo** [comment]
I'm fine with dropping it too as long as we remove the link from the forum.

**Comment by jolan** [comment]
OK found and removed it from the forum footer.

**Comment by jholdstock** [comment]
@jolan 
The Terms and Rules link still appears here: https://forum.decred.org/help/

**Comment by jolan** [comment]
OK removed that too.

**Comment by jcvernaleo** [comment]
@jolan there was still one checkbox unchecked.  Did we confirm that the readmes (like dcrd) don't mention the wiki?

**Comment by jolan** [comment]
Ah looks like there's at least links to verifying binaries on decred-binaries and decred-release.

**Comment by jholdstock** [comment]
Clone all decred repos ([Credit](https://gist.github.com/caniszczyk/3856584)):

```
jholdstock@thinkpad: ~/code/decred
$ curl -s https://api.github.com/orgs/decred/repos?per_page=200 | ruby -rubygems -e 'require "json"; JSON.load(STDIN.read).each { |repo| %x[git clone #{repo["ssh_url"]} ]}'
```

Check all repos for `wiki.decred.org`:

```
jholdstock@thinkpad: ~/code/decred
$ grep -rci wiki.decred.org | grep -v :0$
decred-binaries/release-notes.md:17
decred-binaries/miners-release-notes.md:6
decred-binaries/paymetheus-release-notes.md:1
decred-release/release-notes.md:1
RFPs/rfp-0004/rfp-0004.md:2
```

So it looks like only three repos have wiki references. `decred-binaries` and `decred-release` were already highlighted by @jolan and @jcvernaleo has said he will take care of those. The last references are in an RFP and we may want to preserve those.

**Comment by jcvernaleo** [comment]
Probably best to leave the rpf one as is and as you said, I'll take care of the ones in -binaries and -release today or tomorrow.

**Comment by jcvernaleo** [comment]
Finished this up with decred/decred-release#94 and decred/decred-binaries#39

**Comment by jcvernaleo** [comment]
Once we get @dajohi to kill the wiki and point the subdomain to the same place as docs.decred.org I'll close this.

**Comment by jcvernaleo** [comment]
wiki,decred,org now points to docs.decred.org (thanks @dajohi !) so I'm closing this.
