### ISSUE TITLE
Document how to provide a new translation

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#174]
Suggestion by @dyrk who is planning to start work on russian docs soon.

Add a brief outline to readme.md on how to contribute a new language to dcrdocs

**Comment by jcvernaleo** [comment]
I like the meta-ness of documenting our documentation :)

**Comment by jholdstock** [comment]
I will also include a description of how to host the various different languages. ie. `mkdocs serve -f de_mkdocs.yml`

**Comment by jholdstock** [comment]
[First draft here](https://jbt.github.io/markdown-editor/#fVNdaxsxEHy/X7EkBbeQKGc3Xxz0IQ1NCJQUmryVYulO65OoTjL6iOt/35V8dmwaYvvh5N0Zzc7OVcfHcCOltj0IsLiC6IUNRkTtbFU9KwwIwiNEheCxc8OAVqKEEHEZIDronI1etyniSGCE7ZPoMRdl56XrQlNVUwa3yrnMBjMwGCN6wkqEhfOF/QALH5H1DL7Z3uigQAeYoJ2cwD36Qdhyljj5xOBuRHsMEdyCnqnWJ03EK/ppYyCFjfyfKQRN4N0lwspSKDImPk1YlklulEPWn6skoDBvYQG0Bd4mbeQ8D8eC4gwe7ObqTgRkwDn/fvN4/+WIiDEc0RHabB6BD0vgU66Wi2/dcg18+FNI14PhWQH3ab7/V9bc6xcEHekZ8C/tiyRaBJ6b5lL7Jssv0iZ8x5snKR0cqAW76Py6rM+joNXxEVEAz2MESKDo1MZVhEF40rGysNBmNGELYoeo3B1FazBDcz7QxgDtGtJSUrAoarlDocix2zHtTfk/XUczeN2rCORhyMt7A1VRlp/Qv+QbxuTtxzlUT3pYmjV5brc+Q6B+hNMFSJy/uqztGKqlC7pY5Z2LJxBSG6KOqQzBDyArHdUo1S50X1zaZXsXubVL1EmJJuspl6yqaPutCKr6AO8oqh4e734AfU4BvubklRFdl+htjGU4xth+061BYXMTycfXjVe/HmB6WZ/XM5heNBd1c/55c59vZlfT3zv3nAUV47I5O5vOrlhN32lzXdf1W3hFkTToQ3NxTQRR+AgrETuVeToq0hvzLuyy3sIkRpK5jyNz/gE=). 

@jcvernaleo @karamble anything you would like to add or change?

**Comment by jcvernaleo** [comment]
Would be a little easier if you did this as a PR so I could comment line by line.  But I'll try to give some comments here.

**Comment by jcvernaleo** [comment]
`Choose a 2 letter code for the new language`

You really should not choose the 2 letter code, the codes are a standard https://www.loc.gov/standards/iso639-2/php/code_list.php

**Comment by jcvernaleo** [comment]
`Copy the docs directory to create ru_docs`

If this is a whole new language the build script can do this for you (and probably should).

**Comment by jcvernaleo** [comment]
Need a step 8 where you run the build script again to make sure no errors.

**Comment by jcvernaleo** [comment]
`Serving dcrdocs translations`

That should be 'locally' serving or something like that since this is not how you would ever serve in production.

**Comment by jcvernaleo** [comment]
You need another section for working on an existing translation to mention that you need to make sure the file is caught up with the english version before you work on it.  Maybe mention `git log FILENAME` to look for changes in the english one if a file is already translated or partially translated.

**Comment by jcvernaleo** [comment]
Finally, since this is going in the README.md, you should give make this all under a 2nd level header `## Translations` or something like that and move all of these sections to third level `###`

**Comment by jholdstock** [comment]
Thanks for the comments @jcvernaleo - I have taken them on board and created a PR for a second review.
Would be great to get a review from @karamble as well as he has actually been working on a translation.
