### ISSUE TITLE
need to migrate mathjax to a different CDN

### ISSUE THREAD

**Issue by jolan** [decred/dcrdocs#179]
https://www.mathjax.org/cdn-shutting-down/

**Comment by gozart1** [comment]
I managed to get mathjax loading from same origin by adding the entire mathjax dependencies locally.

But I never made a PR for it b/c the only way I could manage to workaround the live reload issue referenced here https://github.com/decred/dcrdocs/issues/49 was to run the doc server via `mkdocs serve --no-livereload`

I can make a PR for this if folks think that's a reasonable compromise

**Comment by jcvernaleo** [comment]
@gozart1 I've never really seen the livereload work very well anyway.

How much extra stuff do we need in the repo if we do add mathjax?  I saw some talk about how to slim things down in that like from @jolan.  I'd of course be happiest if we could make that monstrosity as slim as possible.

Also, do you know if there is a way to specify --no-livereload as the default (in the .yaml file maybe)?  That would make this solution even nicer.

That said, I'm in favor of no external js if we can.

**Comment by jholdstock** [comment]
There's a solution for this which maintains the live reload functionality in the PR above. The PR includes a detailed description of the changes so I won't duplicate it here. I haven't spent long on this (I already had the first commit and the second is just the output of a 'sed' command) and I won't spend more time on it unless we decide its the approach we want to take as I know @gozart1 has a potential solution as well.

**Comment by gozart1** [comment]
@jholdstock Nice! Your PR looks pretty much exactly what I had + the additional clever sed hack.

**Comment by jcvernaleo** [comment]
This should have been closed with #185
