### ISSUE TITLE
Make placeholders for user input (passwords, etc) consistant

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrdocs#182]
We are completely inconsistent in how we should that something in an example needs to have a user specified value.  I have seen (and done) things like:
```
dcrctl -u USER -p PASS getblockcount
```
```
dcrctl -u USER -p sekret getblockcount
```
```
dcrctl -u 'USER' -p 'PASS' getblockcount
```
```
dcrctl -u <USER> -p <PASS> getblockcount
```

We need to pick one and update all the docs to use it.  Suggestions are welcome.  I hate the use of quotes to indicated it (I've seen that trip up users too many times) so that is off the table.  I'd prefer `<USER>` myself but could be convinced of others.

**Comment by jholdstock** [comment]
`<USER>` gets my vote. It's a common way of doing it and is also used by [Bitcoin](https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list), [Ethereum](https://www.ethereum.org/cli) and [Dash](https://dashpay.atlassian.net/wiki/display/COMMUNITY/Dash+Command-line+arguments), so I think most CLI literate users should understand.

**Comment by jcvernaleo** [comment]
Since we both agree and no one else voiced an opinion, I saw we go with it.

**Comment by jholdstock** [comment]
I'll pick it up now
