### ISSUE TITLE
Panic: Runtime Error: Slice bounds out of range

### ISSUE THREAD

**Issue by gmmethekeys** [decred/dcrdocs#19]
Running into this error while trying to do anything! I am using Windows 7 x64. Using the right version. 

![2016-06-09_1704](https://cloud.githubusercontent.com/assets/6022008/15950504/61fb3390-2e64-11e6-9fb1-0da2110bbe0e.png)

**Comment by jolan** [comment]
This is the dcrdocs repo.  Can you open a new issue on dcrd and close this one please?

https://github.com/decred/dcrd/issues

Also, please include the version that you're running (i.e. 0.1.3, 0.1.4, 0.1.5).
