### ISSUE TITLE
Switch between translations

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#194]
As we now have a PR for french translation pending review (#189) and we will soon have German docs as well, it's about time we starting thinking about the UI for changing between languages.

I think it's already been agreed that the various languages will be hosted like:
- English at `docs.decred.org`
- French at `docs.decred.org/fr`
- German at `docs.decred.org/de`

In the short term we can just give people the URL for the language they need, but really a user should be able to select the language themselves using some simple GUI within the site.

This probably will need input from the designers to make sure we implement this in a way which fits in with their vision of the site.

**Comment by karamble** [comment]
I am allready thinking about that and in my mind the following solutions manifesting:
Using small famfam ico sets for the language flags, i see them more at the bottom of the navigation bar on the left hand.
FamFam Flags here:
http://www.famfamfam.com/lab/icons/flags/

I would like see a small javascript that takes the current url, breaks it up and renders the needed URLs. As all filenames/urls are consistent over the various languages it would be possible to link specific sub.pages to their respective translation just by editing the language-string.

example note to break up an url into peaces easily:
`var languageURL = window.location.protocol + "//" + window.location.host + "/" + window.location.pathname;`

**Comment by jcvernaleo** [comment]
Would a solution like that degrade gracefully with no javascript?

My initial thought was also to have some flag type thing like your idea (bottom of the left nav bar seems good to me) and just have it link to the main docs page for each language.  A little less fancy than yours though.

**Comment by dajohi** [comment]
This will be handled differently.
