### ISSUE TITLE
update docs for gominer 1.0.0

### ISSUE THREAD

**Issue by jolan** [decred/dcrdocs#201]
1.0.0 is coming out any minute.

There should be a note on the Linux docs for the CUDA version.  Previously people would run into this problem:

```bash
$ ./gominer 
./gominer: error while loading shared libraries: libcudart.so.8.0: cannot open shared object file: No such file or directory
```

Basically the CUDA runtime library is packaged in the CUDA SDK which is a 1GB download.  So now this library is included but they need to run "./rungominer.sh <args>" instead and it will load the library from the current directory.

Related issue:  https://github.com/decred/decred-binaries/issues/37

**Comment by guyhalestorm** [comment]
I'll take this one.

**Comment by jcvernaleo** [comment]
Great, thanks!
