### ISSUE TITLE
Add mainnet voting guide

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrdocs#204]
Can probably take a whole lot from `getting-started/user-guides/testnet-voting/`

**Comment by davecgh** [comment]
I answered with a very basic guide for setting up dcrwallet with the vote choices on reddit.  Copying important parts here for reference:

Show your vote choices (preferences) with:

> $ dcrctl --wallet getvotechoices


Set your vote choices (preferences) with:

> $ dcrctl --wallet setvotechoice sdiffalgorithm yes

> $ dcrctl --wallet setvotechoice lnsupport yes

The valid choices for both are "yes", "no", and "abstain".  You can see the available choices via `dcrctl getvoteinfo 4` as well, but I listed them here for convenience.


Finally, show your vote choices again and look at the "choiceid" field to verify they were changed:

> $ dcrctl --wallet getvotechoices


-------

When using a pool, you will need to go the pool's website and set your preferences through its web interface.  However, do note that not all pools are updated yet, so they might not be showing them yet.

**Comment by raedah** [comment]
I suggest mentioning that the user choices are saved to a db, unlike most other settings that only exist on a per session basis unless put in the config file.
