### ISSUE TITLE
Move from updated for vX.X.X to 'last updated'

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrdocs#205]
It has been suggested that the version number in 'last' updated are more confusing than anything else since we either have to update each time we have a version bump as long as the info is still correct (which is weird since we haven't changed most of those pages) or we have docs that list a ton of different versions and look confusing.  Just dates in most places would probably be clearer.

**Comment by jholdstock** [comment]
I think dates would probably be better, but are either really necessary? I'm not sure how useful it is to the public, it is a pain to maintain, and if necessary we can see the modification history on github.

**Comment by gratefulcheddar** [comment]
I agree that dates are better.

**Comment by jcvernaleo** [comment]
@jrick since you brought this up initially, do you have a preference for dates vs nothing (since we all agree that versions are not good now).

**Comment by jrick** [comment]
If it's unrealistic to make sure all doco is always kept up to date all of the time (spoiler: it is), we should have dates.

**Comment by jcvernaleo** [comment]
Well, hopefully our interface doesn't change enough for docs to need changing all the time but fair point.

**Comment by jrick** [comment]
Instead of a date that changes every time, another alternative is "last updated for version X.X.X"

**Comment by jcvernaleo** [comment]
Someone requested the date for last updated in the docs survey.

**Comment by jolan** [comment]
Doesn't sound like this will be happening.
