### ISSUE TITLE
Enable pos from wallet

### ISSUE THREAD

**Issue by BatuhanUsluel** [decred/dcrdocs#22]
Hello, while I was following your Proof Of Stake guide from docs.decred.org I experienced some problems and couldn't vote my tickets. I then figured out that you had to add --enablestakemining when starting your wallet but the documentation doesn't state this on that page. Even though it may be a very basic thing, its hard to figure out that you had to add that when it doesn't write it on the documentation. It would be helpful for other people following the documentation that you add the --enablestakemining command.

**Comment by jcvernaleo** [comment]
This has been covered in the recent changes to the docs.
