### ISSUE TITLE
Paymetheus incorrect balance guide needs updating.

### ISSUE THREAD

**Issue by gratefulcheddar** [decred/dcrdocs#221]
https://docs.decred.org/faq/errors/#4-paymetheus-is-displaying-the-wrong-balance

This does, in fact, work for 1.0.1, so the warning can be changed.

It may also be beneficial to add a step between 14 and 15 that instructs user to import their stakepool script, if they've used a stakepool before. 

Something like "retrieve 'redeem script' from stakepool's tickets page, issue `./dcrctl -u <username> -P <password> --wallet -c $env:localappdata/decred/paymetheus/rpc.cert importscript <redeem script from pool website>`"

**Comment by jolan** [comment]
Superseeded by #316.

Closing.
