### ISSUE TITLE
es_mkdocs.yml out of date

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#223]
`es_mkdocs.yml` is missing:
- Decrediton Setup
- Inflation
- User Projects

The `.md` files are all present, its just the `.yml` files out of date

**Comment by jholdstock** [comment]
@jcvernaleo despite Github now recognising me as a dcrdocs project contributor I still cannot add labels to issues. I was going to add `Bug` to this one. Are you able to grant that permission or is it hard coded behaviour?

**Comment by jcvernaleo** [comment]
I have no idea why github doesn't like you.  There is no special permission I can set, it is normally just a contributor or not contributor thing.  I'll set this as bug and assign to you and then review the PR where you already did it :)
