### ISSUE TITLE
Add daves seed explanation from reddit

### ISSUE THREAD

**Issue by fai04d** [decred/dcrdocs#227]
https://www.reddit.com/r/decred/comments/68go1n/understanding_the_33_seed_words/dgyeiu9/

**Comment by jolan** [comment]
This is mostly covered already by:

https://docs.decred.org/faq/wallets-and-seeds/#5-can-someone-use-a-brute-force-attack-on-a-random-wallet-to-regenerate-its-seed-words-the-words-are-not-salted

I do think that section could be improved a bit.  The first item on the list should probably explain what a seed is and maybe go into some detail about how all accounts/addresses are derived from it in a deterministic fashion.

**Comment by dajohi** [comment]
Open a new issue for what is still needed.
