### ISSUE TITLE
Video tutorials

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrdocs#229]
I'm not sure I consider video to be part of docs but not sure where else to put this.  The suggested possible video topics are:
 1. Explanation of Decred
1. Use cases
1. PoS mining (MANY ANSWERS)
1. “How to make your wallet as safe as possible?”
1. “The focus should NOT be on making a tutorial on how to setup software on wallet, work mining, or stake mining. Decred right now would benefit most by creating more well produced exapnded versions of the topics shown in the "Decred Intro" posted on YouTube by D3C RED. Basically take the things in the powerpoint presentations and make it look pretty and put music to it. Explain the bullet points in more detail.”
1. Explaining advantages of governance
1. PoW mining, all software
1. Using CLI
1. CLI Installation
1. Getting started with Web Wallet
1. Jordan Peterson
1. Voting
1. How to buy DCR
1. Coinbase presentation
1. Promo videos
1. Updating software
1. Using Paymetheus/Decrediton
1. Raspberry Pi
1. Wallet Management in CLI
1. Tutorials like Ethereum’s

We already have issue #40 open for an install video.

**Comment by jcvernaleo** [comment]
It was also requested that videos have english subtitles (to aid translations).

**Comment by jholdstock** [comment]
Maybe close #40 as a duplicate? This one contains much more info

**Comment by jolan** [comment]
We have a pretty clear downloads page which links to GUI installers first so I don't think this really makes sense anymore.
