### ISSUE TITLE
Raspberry pi tutorials

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrdocs#230]
Although it  is basically the same as other unixes, people have asked for rpi tutorials.  Probably could start with what is and what is not a good idea to do with an rpi for decred.

**Comment by jcvernaleo** [comment]
Might also need to call out which binary is used for it.

**Comment by jholdstock** [comment]
@dajohi  Personally I would close this one off - my reasoning would be that setting up a node on raspberry pi is no different to any other unix - I could be wrong about that though?

If there is any significant difference, maybe it could be just an FAQ entry - Can I run a Decred on a rasberry pi?

**Comment by dajohi** [comment]
Agree.
