### ISSUE TITLE
Link to release notes?

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrdocs#232]
Someone asked for detailed release notes.  We already have detailed (possibly too detailed) release notes on github.  Maybe we could link to them (and maybe the release announcements too).

Not sure what the best thing to do here would be.

**Comment by jholdstock** [comment]
Im not sure dcrdocs is the correct place for detailed release notes - @dajohi  I would suggest closing this

**Comment by dajohi** [comment]
I agree.
