### ISSUE TITLE
Compiling from source

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrdocs#235]
In most cases this is gone through very well in the README files on github.  We could include that here or (even better in my opinion) have a smaller page on building and then link to the relevant sections in the github READMEs since I do not think duplicating things is a good idea.

Some of this is also in https://docs.decred.org/advanced/contributing/ already (but that would not be obvious for someone trying to just build the software).

**Comment by jolan** [comment]
Rolling into #431.
