### ISSUE TITLE
add how to file quality issues to github/contributing section

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrdocs#236]

**Comment by jcvernaleo** [comment]
I think the contributing part is already covered pretty well in https://docs.decred.org/advanced/contributing/
Is there some other getting involved info we need or should we close this?

**Comment by gratefulcheddar** [comment]
This covers technical involvement/development pretty well but I think other areas of contribution should be covered too. 

Leaning towards the technical side, a quick run-down on how to submit Issues through GitHub and/or edit files within the browser might be helpful. 

I think we should get marketing involved too. A section for how community members can help them.

**Comment by gratefulcheddar** [comment]
Per raedah in Slack, "I don't see anything in the docs about how to file bug reports and feature requests."

**Comment by jcvernaleo** [comment]
I'm closing this issue as super out of date.
