### ISSUE TITLE
Compare decred to other currencies

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrdocs#237]
More than one person mentioned this so I'm opening the issue if we want to discuss it but I very strongly object to adding such a thing to docs.  The docs should be about why decred is good (really it should explain decred features, etc, but hopefully that says why decred is good as well).  If marketing/pr people want to compare to other coins in other venues that is fine and probably makes sense, but I don't think it belongs in docs.

**Comment by raedah** [comment]
I have seen something of the sort done well, on the arch wiki.
https://wiki.archlinux.org/index.php/Arch_compared_to_other_distributions
The trick seemed they kept it matter of fact rather then opinions or judgement.
An examples would be how bitcoin and decred both have a 21 mil coin supply cap, but decred reduces the block reward by 1% every 21 days, while bitcoin halfs the reward every 4 years. Factual, undebatable, and does not offend anyone.

**Comment by jcvernaleo** [comment]
Done that way (very factual) and I would be totally in favor of this and think it would be a great thing to have.  I just do not want this to turn into an advocacy thing trying to say why decred is better or anything like that.

**Comment by jholdstock** [comment]
https://en.wikipedia.org/wiki/List_of_cryptocurrencies
https://en.bitcoin.it/wiki/Comparison_of_cryptocurrencies

These could be useful if we go ahead with this - personally I am quite indifferent about the idea

**Comment by jolan** [comment]
This was implemented on the main website:

https://decred.org/compare/
