### ISSUE TITLE
News section

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrdocs#238]
This is another one that I'm putting in since it was suggested so we should discuss but personally I think the main webpage is a better fit for that rather than the docs page.

**Comment by jcvernaleo** [comment]
That said I like the idea of a news section.

**Comment by jholdstock** [comment]
Maybe close as a duplicate of #138?

**Comment by jcvernaleo** [comment]
Agreed, #138 covers this and more (and it has some links listed already) so closing this one.
