### ISSUE TITLE
finances/dev subsidy, etc.

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrdocs#245]
A few requests for something about this:
Transparency stuff, finances, The mechanism for how the developer money gets distributed.

**Comment by jholdstock** [comment]
I think we already cover some of this in

https://docs.decred.org/advanced/inflation/
https://docs.decred.org/faq/general/#3-how-was-the-decred-premine-distributed

As for the mechanism of how dev funds are distributed, I think the recruiting blog post spells that out quite well.

And seeing as a lot of this stuff will be changing when Politiea is released to production, I'm not sure theres great value in progressing it right now. @dajohi I suggest closing this one.

**Comment by dajohi** [comment]
Agree.
