### ISSUE TITLE
history/origin

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrdocs#246]
There was a request for "Decred history, origin story." and "Dev team creation history".

**Comment by jholdstock** [comment]
Not sure if docs is the correct placee for this kind of thing personally.

There is a already a length and detailed decred digest blog post  https://thedecreddigest.com/2017/08/11/the-road-to-the-decred-dao-a-self-funding-cryptocurrency/

**Comment by jolan** [comment]
Could also mention that Decred was derived from a portmanteau of decentralized credit.

**Comment by xaur** [comment]
Another good article about the origin https://thedecreddigest.com/2017/06/10/decred-where-did-it-all-begin/

**Comment by s-ben** [comment]
FYI, Dustorf (don't know his GitHub handle) is putting together a new page on decred.org that outlines the history. When that comes out, we could just link to it from the docs?

**Comment by jcvernaleo** [comment]
That seems like a reasonable place to me.  I had no strong desire for it to go in docs but a link would be nice.

**Comment by s-ben** [comment]
Will keep my eye out for it and link to it when it's up 👍

**Comment by xaur** [comment]
FYI there was also a collaborative attempt at collecting the timeline here: https://github.com/artikozel/decred-timeline

And a gist from jz here: https://gist.github.com/jzbz/80781fd7d29614994cb5d78e4610a972

**Comment by s-ben** [comment]
While I agree with @jholdstock about the docs not being the most appropriate place for this, it could be a nice addition to the list of resources we provide in the [beginner's guide](https://docs.decred.org/getting-started/beginner-guide/). We could put it in the `News/Articles` section after the decred cannon, or perhaps in a new section called `History` or something.

**Comment by xaur** [comment]
Another possible place to host the history is a community-curated wiki which I plan to start at some point. If that sounds interesting I can accelerate it.

**Comment by s-ben** [comment]
I like wikis personally. I've already shared the [Decred Canon](https://github.com/maxbron08/Decred-Canon) a couple times. Also there is a lot of information/resources that aren't appropriate for the docs, but that might be useful to have somewhere.

**Comment by jholdstock** [comment]
Closing this - almost all of the suggestions above have been implemented in the [decred.org history page](https://decred.org/history/) or the [docs Articles and Media page](https://docs.decred.org/getting-started/articles-and-media/)
