### ISSUE TITLE
sgminer docs

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrdocs#247]
Since we do not develop (or even provide binaries for) sgminer, I don't think this should be added other than some very basic info or a link to other sites, but others might disagree.

**Comment by jholdstock** [comment]
We mention sgminer in the unofficial miners section: https://docs.decred.org/mining/proof-of-work/#unofficial-miners

Suggest closing this @dajohi

**Comment by jolan** [comment]
Agreed, closing.
