### ISSUE TITLE
How to connect with javascript

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrdocs#255]

**Comment by jholdstock** [comment]
The full survey response was:

> Technical: How to connect to wallet/daemon via Javascript

I feel like this is something which does not belong in dcrdocs - suggest closing this issue.

**Comment by jcvernaleo** [comment]
Back in the early btcsuite days I wrote and shared little snippets for how to connect to the daemon over the old json-rpc api on multiple occasions.  I tend to think that docs would be a good place for an updated version of that.  I think wallet may even ship with some examples so it might be sufficient to just link to them.

**Comment by jholdstock** [comment]
@dajohi  suggest closing this - I dont think there is demand for it

**Comment by jolan** [comment]
Agreed.
