### ISSUE TITLE
Unable to create wallet

### ISSUE THREAD

**Issue by daehbew** [decred/dcrdocs#26]
Hello, I have an email stating that "
You recently signed up for the Decred airdrop. The project is delighted to let you know your application has been successful!" I followed the steps at the time and created a seed and hex address. When I go to https://wallet.decred.org/#/ to try and create a wallet I keep getting an error.

I deleted the generic wallet that had already existed. There was no balance on that first wallet. I then tried to create the wallet with the seed by "create a new wallet." When I go to advanced options; there is nothing that specifies a seed so I used "Specify Recovery Phrase." however, when I input the seed here and name my wallet etc, I get an error that says, "Error creating wallet: Network connection error."

Can you guys please advise me on this. Am I doing the correct steps to generate this wallet? Is the network  just down at the moment? If yes, when will it be back up?

Very Respectfully,
Matthew Spano

**Comment by jolan** [comment]
Hi,

Yes, you appear to be doing things correctly.  There was indeed a problem with the wallet service which caused that error.  The wallet service is running again now.  If you need further support to access your funds, the [Decred Forum](https://forum.decred.org/) would be the preferred place to ask for assistance. Typically the GitHub issue tracker is used for code or documentation.
