### ISSUE TITLE
More security warnings about private keys, scams, etc

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrdocs#260]

**Comment by fai04d** [comment]
I don't know how we improve this. There's already warnings on wallet creation, in the forums and the docs are quite explicit here too. As for scams, we've already got notes in the Slack. It's not really our job to teach common sense (i.e. don't send funds to people you don't know).

**Comment by jcvernaleo** [comment]
I'm not sure it even is possible to teach common sense unfortunately.

**Comment by jolan** [comment]
I agree that this is not actionable.
