### ISSUE TITLE
Where to spend DCR

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrdocs#261]
This is another that I have mixed feelings about for docs but might be great on main page.

**Comment by jcvernaleo** [comment]
Similarly: Official sites who support/use Decred

**Comment by jholdstock** [comment]
Agreed - It would be nice to have a curated list of these things but I don't think it belongs in the documentatoin

**Comment by jcvernaleo** [comment]
@jolan would you object to me closing this issue and opening a copy of it on the dcrweb repo?

**Comment by jolan** [comment]
That's fine with me, go ahead.
