### ISSUE TITLE
Technical details

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrdocs#264]
“Technical details, e.g. how is a Decred Address formed (see for example https://en.bitcoin.it/wiki/Technical_background_of_version_1_Bitcoin_addresses), what are the outputs in a stake transmission and so on. But this might be better for later, since you should focus on normal users for now (as you are doing). Developers can in the meantime look at the sourcecode.”

**Comment by jolan** [comment]
Not really against this but I have never seen any demand for this either.  Maybe this could be covered by #431.
