### ISSUE TITLE
simplify PoS/PoW material and add voting lifecycle images

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrdocs#272]
“It’s hard to understand the difference and meaning of Proof of Work and Proof of Stake. How do I show proof of stake? Ideas and concepts like this need to be distilled to just a few sentences, not paragraphs. You need to help the "average" person understand this so they understand what they're getting into, but easily. Although the "Proof of Work" section says "As you can see, it's quite simple", the next thing it does is list a 9-step process with a lot of jargon. Why would a user want to vote on a PoW block? What does it mean to vote? Do I go to a website to vote? It's a hard concept to understand. This is something that I, personally, see as a huge barrier to new people.”

**Comment by jolan** [comment]
We have those stakey images and whatnot now so this seems doable.  I do agree, it is a lot of jargon and pointing people to this section usually just leads to more questions.

**Comment by jholdstock** [comment]
Closing this one - very old and most of the PoS and PoW material has been rewritten since this was opened.
