### ISSUE TITLE
Better organization for download and install

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrdocs#273]
Easier to find paymetheus download/install page.

**Comment by jholdstock** [comment]
I have wanted to change this for some time now actually. I don't like the "Download and Install" page at all, I think the instructions to download+install paymetheus belong in the Paymetheus section.

Currently setting up Paymetheus requires visiting three different page in three different sections of the website.
1. https://docs.decred.org/getting-started/beginner-guide/#paymetheus-path
1. https://docs.decred.org/getting-started/install-guide/#paymetheus
1. https://docs.decred.org/getting-started/user-guides/paymetheus/#paymetheus-setup-guide

I think we would have a better experience if we could have:
1. Getting started page - allow the user to pick the software they need (eg paymetheus)
1. Straight into the Paymetheus section, which includes all info needed

Obviously the same applies to CLI and decrediton.

**Comment by jholdstock** [comment]
Would appreciate some feedback on the PR.

Note that it removes the file `install-guide.md` and in it's current state will leave the old URL as a `404`.
