### ISSUE TITLE
dcrstats api

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrdocs#279]
Not our page so I really do not think we should add it.

**Comment by fai04d** [comment]
Agreed. If we add that here it creates a strong official link to dcrstats and by extension, Evolution. I have no problem linking to third parties (with disclaimers), but we should not be providing documentation for them.

**Comment by jholdstock** [comment]
Agreed that we should not include dcrstats/evolution etc in dcrdocs. 

I don't believe https://stats.decred.org/ presents any API but I'm not sure. If we can confirm then I think this should be closed.

**Comment by jolan** [comment]
Closing since dcr-netstats doesn't have an API and we're all in agreement about dcrstats.
