### ISSUE TITLE
update stake pool list

### ISSUE THREAD

**Issue by jolan** [decred/dcrdocs#283]
Need to https://ultrapool.eu to https://docs.decred.org/mining/proof-of-stake/#list-of-stakepools

**Comment by jholdstock** [comment]
I'm curious whether the following took place:

> Company 0 will verify each stake pool configuration is proper before moving to mainnet. Unprivileged shell accounts will be made available so the configuration can be verified after running for 1 week on testnet.

> The operator must demonstrate their monitoring solution by temporarily sending alerts to a specified email address. An example monit configuration will be supplied to avoid requiring operators to setup their own monitoring solution from scratch. After this has been verified, the pool will be opened to the public.

[_(source)_](https://forum.decred.org/threads/rfp-6-setup-and-operate-10-stake-pools.1361/)

If stakepools are listed in the docs, people may interpret this as an official endorsement from the Decred team. I personally think there should be some vetting of the pools before they are endorsed in this manner.

**Comment by jolan** [comment]
Yes the pool was vetted in that manner.

Also, we need to remove a pool -- https://dcrstakes.com/

They went through a changing of admins and haven't been able to upgrade and have 0 live tickets.
