### ISSUE TITLE
FAQ Useful Links

### ISSUE THREAD

**Issue by raedah** [decred/dcrdocs#284]
I would like to see a section in the docs for useful resources. At minimum it should include the links that are on https://decred.org/. Here are others that may be worth including as well.

Alternate block explorer - http://yiimp.ccminer.org/explorer?id=1574
Decred public node list -https://decred.monkeyland.io/online.shtml
Market list - https://coinmarketcap.com/currencies/decred/#markets
Official block explorer - https://mainnet.decred.org
https://dcrstats.com/
https://forum.decred.org/
https://docs.decred.org/
https://voting.decred.org/
https://stats.decred.org/
https://github.com/decred
https://decred.slack.com/
https://www.reddit.com/r/decred/
https://twitter.com/decredproject

**Comment by dajohi** [comment]
https://en.wikipedia.org/wiki/Decred

**Comment by jholdstock** [comment]
https://docs.decred.org/advanced/user-projects/

This page already covers some of the above. It is quite hidden away within the site, so maybe we could make it a bit easier to find. 

Any thoughts about how to expand the existing page, or do we want a new page?

**Comment by jolan** [comment]
So a couple of the links are dead now, some of these are already mentioned where they are relevant, and some are present in the new design.

Could probably just add a link to the main website to the footer and close this out.
