### ISSUE TITLE
Confusing download links

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#286]
The latest release version of Paymetheus is 1.0.1. [The Paymetheus download link here](https://docs.decred.org/getting-started/install-guide/#paymetheus) points to the latest release in the `decred-binaries` repo. This happens to be 1.0.2 which only introduced a new version of decrediton. Paymetheus 1.0.2 does not exist and this could lead to confusion.

We could update the links so instead of pointing to the latest release they point to the release tag. 

For this particular case the change would be to use:
https://github.com/decred/decred-binaries/releases/tag/v1.0.1
instead of 
https://github.com/decred/decred-binaries/releases

Thoughts?

**Comment by jholdstock** [comment]
Bug label please -_-

**Comment by jolan** [comment]
Yes this has been a problem for a long time unfortunately.

We should have a downloads page on the website soon so hopefully all links can become decred.org/downloads/#decrediton or similar.

https://github.com/decred/dcrweb/issues/36
