### ISSUE TITLE
Include PoW mining examples for every pool

### ISSUE THREAD

**Issue by gratefulcheddar** [decred/dcrdocs#30]
Brought up by praxis. 

Having examples for other mining pools may help spread out hashing power. 

https://docs.decred.org/mining/proof-of-work/

**Comment by gratefulcheddar** [comment]
I've tasked myself to this.

**Comment by jholdstock** [comment]
I think this can be closed now @gratefulcheddar?

It looks like we have a good list of pools on the PoW page currently: https://docs.decred.org/mining/proof-of-work/

**Comment by jcvernaleo** [comment]
Confirmed with @gratefulcheddar that this one can be closed.
