### ISSUE TITLE
build_docs.sh output/return code

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#300]
Two goals here:

- When a dev runs the script its not obvious at a glance whether it has succeeded or failed. This can be improved by:
    - Stopping the build when the first error is encountered
    - Outputting a clear success/failure message

- Get the script ready for CI
   - Currently the script returns exit status 0 regardless of what happened in the run. We need to return a non-zero code when an error occurs

**Comment by jcvernaleo** [comment]
One comment is I do no think there should be a message for success.  If anything I'd like to get rid of most of the current output unless there is a problem.

In the ideal case I'd want to see something like:
```
Building docs.
Building es docs
...
```
and nothing else unless there is an error.  But that might requiure more shell redirection trickery than you want to do.  If we really want to preserve the old output maybe hide it behind a `-v` flag or something.

**Comment by jholdstock** [comment]
Adding both a success and a failure message was purely habitual - having given it some thought I like the idea of removing the success message. Having success output and fail output being more distinct from each other will help to make it even more obvious when something has gone wrong.
