### ISSUE TITLE
Move "manual install/configure cli tools" to "Advanced" section

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#304]
Currently the sections for `dcrinstall` and manually installing/configuring the CLI tools is on the same page. (https://docs.decred.org/getting-started/install-guide/)

`dcrinstall` is the method we recommend for most users, and configuring manually is only recommended for advanced users.

Moving these instructions to their own page in the Advanced section should hopefully increase the amount of people choosing `dcrinstall` and  reduce the amount of time spent supporting users with the manual configuration process.

**Comment by jcvernaleo** [comment]
I think this split is a good idea.
