### ISSUE TITLE
URL structure and dead links

### ISSUE THREAD

**Issue by karamble** [decred/dcrdocs#309]
Users claim there are dead links in the google search index.

![image](https://cloud.githubusercontent.com/assets/25404928/26477852/c0ba32aa-41c8-11e7-9d61-6a8cb4169a8f.jpg)

**Comment by jcvernaleo** [comment]
I think we settled on the best solution being to do 301 redirects for some specific pages that have moved and a general 404 redirect going to the main page for other missing pages.

@karamble is going to make the list of 301 redirects and then @dajohi will get them going on the server.

If I missed anything (or got something wrong, please update the issue).

**Comment by dajohi** [comment]
web crawlers/bots should be doing it themselves.
