### ISSUE TITLE
documents data paths for all software on all OSes

### ISSUE THREAD

**Issue by jolan** [decred/dcrdocs#323]
Would be nice to have a FAQ entry about all the various paths for all the various software on all the various OSes since this comes up quite often.

So document where the command-line installer/Decrediton/Paymetheus put the binaries/config/data on Windows/macOS/Linux and note their role/significance.

Mostly this comes up when someone wants to delete their wallet.db and restore from seed.  So should
probably explicitly mention verifying that they have their seed first or at least recommend renaming wallet.db rather than outright deleting it.

**Comment by jcvernaleo** [comment]
We have this already:
https://docs.decred.org/getting-started/cli-differences/
If there is something it doesn't cover maybe it can be added there.

**Comment by jcvernaleo** [comment]
Or if we do need a new page (since that is cli specific) the new page should be very similar to that.
