### ISSUE TITLE
Add shapeshift to the "exchanges" section of 'obtaining dcr' in the getting started guide

### ISSUE THREAD

**Issue by pvtwarren** [decred/dcrdocs#328]
https://docs.decred.org/getting-started/obtaining-dcr/#exchanges

Should probably also mention that Shapeshift doesn't require an account

**Comment by bebrites** [comment]
Shapeshift, Changelly, Evercoin, flyp and https://www.altcoin.io/

**Comment by jholdstock** [comment]
ShapeShift, Changelly and Evercoin are already added. 

altcoin.io appears to just be a flashy marketing site with no actual product behind it.

I will add flyp.me
