### ISSUE TITLE
Improvements for the section 'Obtaining DCR'

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrdocs#330]
Here are possible changes for https://docs.decred.org/getting-started/obtaining-dcr/#obtaining-dcr

- Remove the sentence "_Bitcoin must be traded for Decred, fiat currency cannot be used_"
- "_We hope this list will grow as time goes on_." The list has grown, for example Tux Exchange
- Add the **arrow icon** of 'Exchanges' to 'Direct Exchanges' as well (to make it more equal)

(and, as pvtwarren mentioned, add ShapeShift to the list)

**Comment by jholdstock** [comment]
I noticed the first two points myself and fixed them in #417.

I have addressed the third point by removing the icons from all headers in #427 - they seemed to just be there for the sake of it and didn't add much.
