### ISSUE TITLE
Sample config file docs link broken 

### ISSUE THREAD

**Issue by davecgh** [decred/dcrdocs#337]
URL in [documentation](https://docs.decred.org/faq/configuration/) ([github source](https://github.com/decred/dcrdocs/blame/master/docs/faq/configuration.md#L32)) links to a file that no longer exists:

[sample config file](https://github.com/decred/dcrd/blob/master/sample-dcrd.conf)

It is now [part of the code](https://github.com/decred/dcrd/blob/master/sampleconfig/sampleconfig.go#L7-L339).

Reported by @johnerfx in decred/dcrd#803.

**Comment by jholdstock** [comment]
The same sample config file is also mentioned on this page, step 2 under the heading "Minimum Configuration"

https://docs.decred.org/advanced/manual-cli-install/

**Comment by jolan** [comment]
When fixing this, we also want to link to a certain commit so the line numbers do not change like so:

https://github.com/decred/dcrd/blob/509eed37fba59b32f815a356fbad94111aab3424/sampleconfig/sampleconfig.go#L10-L531
