### ISSUE TITLE
Include explanation on how ticket fees are calculated

### ISSUE THREAD

**Issue by gratefulcheddar** [decred/dcrdocs#35]
Include explanation on how ticket fees are calculated

**Comment by animedow** [comment]
A general look at and correction of the fee explanations across the docs might be needed. 

For example, it says in the pos-commands:

setticketfee fee	Set the (non-refunable) fee for purchasing stake tickets. See FAQ#Ticket fee
settxfee amount	Sets the fee per kB of transaction data you are willing to pay. Note this is NOT the same as setticketfee above.

setticketfee is also in DCR/kB.

and then in https://docs.decred.org/faq/proof-of-stake/buying-tickets-and-fees/#5-how-should-i-set-the-txfee

it should be ticketfee and not txfee.

**Comment by fai04d** [comment]
I'll take this one.

**Comment by jcvernaleo** [comment]
Great.  Can't assign it to you since you don't have any previous commits (a github 'feature') but it is all yours.

**Comment by gratefulcheddar** [comment]
How does @fai04d not have any commits?

**Comment by jcvernaleo** [comment]
I thought he did but github seems to think otherwise.

**Comment by jolan** [comment]
With the sdiff fix, I don't think we really need to worry about this.
