### ISSUE TITLE
Create a page for all various third-party tools

### ISSUE THREAD

**Issue by gratefulcheddar** [decred/dcrdocs#36]
Create a page for all various third-party tools

**Comment by jcvernaleo** [comment]
We probably want to be careful in this page to make it clear that we don't necessarily endorse or support the third party tools.  Provide a list of links to them could be very useful though.  There should probably be some discussion as to just how curated the list will be though (do we include everything we see, nearly everything, or something else).

**Comment by jholdstock** [comment]
These are the ones which immediately come to mind. 

Dyrk
- https://dcrstats.com/
- https://evolution.dcrstats.com/en
- https://play.google.com/store/apps/details?id=com.ionicframework.myapp554035
- https://itunes.apple.com/us/app/dcrstats/id1141383230
 
Myself
- https://play.google.com/store/apps/details?id=com.jamieholdstock.dcrwidgets

jonathanveg:
- https://play.google.com/store/apps/details?id=altcoin.br.decred

shadowlance
- http://www.posmaster.info/

**Comment by jholdstock** [comment]
_Reviewing the list in the first post at https://bitcointalk.org/index.php?topic=1290358.0_

- [Android Decred Widgets](https://play.google.com/store/apps/details?id=com.jamieholdstock.dcrwidgets)
	- Alive

- [Pydecred](https://forum.decred.org/threads/pydecred.329/)
	- Still on github - not updated >1year

- [Decred J Wallet -- Java Gui Wallet](https://forum.decred.org/threads/decred-j-wallet-java-gui-wallet.382/)
	- Not updated >1year - Many users reporting errors

- ~[PoS Miner Portal](https://forum.decred.org/threads/pos-miner-portal.661/)~
	- Marked "DISCONTINUED" in github

- [Dcrstats.com - Decred Network Dashboard](https://forum.decred.org/threads/dcrstats-com-decred-network-dashboard.809/)
	- Alive

- [Decred Wallet GUI](https://forum.decred.org/threads/decred-wallet-gui.1119/) 
	- Alive

- [D3c.red - Another Decred Dashboard](https://forum.decred.org/threads/d3c-red-another-decred-dashboard.1273/)
	- Alive

- [Bitstream For Ztex 1.15y](https://forum.decred.org/threads/bitstream-for-ztex-1-15y.1342/)
	- I'm not a PoW guy - don't feel qualified to judge this one

- [Bash Shell Script To View Quick Stats On Balance And Tickets](https://forum.decred.org/threads/bash-shell-script-to-view-quick-stats-on-balance-and-tickets.2926/)
	- Looks like it should still work

- ~[Decred Gateway](https://forum.decred.org/threads/decred-gateway.3640/)~
	- Dead

- [Decred Monitor And Data Collector - Dcrspy](https://forum.decred.org/threads/decred-monitor-and-data-collector-dcrspy.3838/)
	- Alive
