### ISSUE TITLE
Is there any plan to translate this doc to Chinese?

### ISSUE THREAD

**Issue by AbnerZheng** [decred/dcrdocs#361]
Hi, I'm a distribute system engineer from China, and I'm interested in decred project. But I'm not quite familiar with the detail of blockchain and decred. I wanna to begin with translating this doc to Chinese,  so is there any plan to translate into Chinese or even someone is doing this thing?

**Comment by jholdstock** [comment]
Hi @abnerzheng

Great to hear you are interested! The best place for translation support would be either the Decred Slack channel or IRC. You can find links at the bottom of the decred homepage https://decred.org/. Once you get in, you will want to speak to either user jz or user ingsoc

Good luck!

@dajohi can we close this issue please.
