### ISSUE TITLE
Inaccuracy in PoS docs

### ISSUE THREAD

**Issue by fai04d** [decred/dcrdocs#387]
> Decred’s PoS also provides a system of checks and balances for nonconforming miners. Stakeholders can vote a block invalid if it doesn’t match to the consensus rules of the network.

Should be, "if it doesn't conform to their collective policy".

**Comment by jholdstock** [comment]
This was fixed in #400.

> Providing a mechanism for stakeholders to keep check of nonconforming proof-of-work miners. Stakeholders can vote a block invalid even if it conforms to the consensus rules of the network. This allows stakeholders to discourage unfavourable mining behavior such as mining empty blocks.

We can close this issue

**Comment by jolan** [comment]
Fixed via #400.
