### ISSUE TITLE
Remove/demote Paymetheus in favour of Decrediton

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#394]
We have two significant pages dedicated to Paymetheus - [one for installation](https://docs.decred.org/getting-started/user-guides/paymetheus/) and [one for usage](https://docs.decred.org/getting-started/user-guides/using-paymetheus/). There are links to those two pages, and other mentions of Paymetheus, peppered throughout dcrdocs. 

I'm thinking that we can: 
- remove the mentions and/or replace them with Decrediton mentions
- archive the two Paymetheus pages somewhere, maybe under "Advanced" or a new "Legacy" or "Archive" section. 
- (optional) create a new Paymethus troubleshooting page, so that more important things ([example](https://docs.decred.org/faq/errors/#4-paymetheus-is-displaying-the-wrong-balance)) can be kept in a single page rather than scattered

**Comment by jrick** [comment]
I would archive them for now with mention that Decrediton is the new hotness.  We're not sure exactly when we'll stop producing binary releases of Paymetheus.
