### ISSUE TITLE
Section about chain parameters, decred numbers.

### ISSUE THREAD

**Issue by raedah** [decred/dcrdocs#401]
Q: What is the PoW retarget time on DCR ?
A: Both PoS and PoW retarget every 12 hours (144 blocks).
ref: https://github.com/decred/dcrd/blob/master/chaincfg/params.go#L484

Q: What is the decred supply limit?
A: 21 million.

Q: How did the premine work?
A:
The premine consists of 1.68 million coins
Premine consists of 8% of the total supply of 21 million coins
Company 0 and its developers have received 4% of the total supply, 840,000 coins (at USD 0.49 per coin). 
The remaining 4% will was given to airdrop participants
You can see the creation of these coins in block 1,
https://mainnet.decred.org/block/000000000000437482b6d47f82f374cde539440ddb108b0a76886f0d87d126b9
Airdrop participants got 282.63795424 DCR each. 2,972 airdrop participants.

Q: How does the block reward work?
A: When a block is mined,
60% goes to the PoW miner
30% goes to the 5 PoS voters
( the 30% is further split between 5 randomly chosen stake tickets which are called to vote via a lottery. Each stake ticket thus would get 6% )
10% goes to the decred developer fund
Each block has up to 5 PoS votes in it, so for every vote that is missing, the PoW miner loses 20% of their reward.
The block reward is reduced every 6144 blocks (21.33 days). The formula is to take the current reward * 100 and divide by 101, which is equivalent to ~99.01%.

Q: How does staking work?
A:
A max of 20 tickets may be purchased (sstx) per block. 
Stake difficultly target, aka ticket price, adjusts every 144 blocks (12 hours on average).
256 block maturity period (average of 21.33 hours) that the ticket must undergo before it is eligible for selection by the lottery. 
It is "a ticket to 40,960 lotteries." The ticket is valid until it is chosen or for 40,960 blocks (target of 142.22 days)(~4.7 months) after which time it expires. There is around a 99% chance the ticket will be selected before expiring.
During this time the coins used to purchase the ticket remain locked.
Statistically the average win time is 28 days (~28.444) (8192 / 144 / 2)  (8192 blocks). 
The target tickets for the pool is 8192*5=40960. It then calculates as % change per window in the ticket pool size. Maximum re-target is a factor of 4.
What happens to a sstx that is not confirmed? Drops out of the mempool and you get back the ticket money but you lose the fees.
sstx = purchase ticket, stake submission ticket (sstx)
ssgen = cast vote

**Comment by jolan** [comment]
Adding more technical info is now being tracked in #431.

History stuff like premine/airdrop is covered by #246.
