### ISSUE TITLE
Documentation on Advanced/ Contribuiting is out dated

### ISSUE THREAD

**Issue by vctt94** [decred/dcrdocs#403]
On One time setup located at https://docs.decred.org/advanced/contributing, the documentation is out dated. It is saying to install dcrd with glide, but we are using dep now.

**Comment by brandonblock** [comment]
I'm interested in tackling this issue to get my feet wet, can I confirm installation process or verbiage? I assume

```
$ mkdir -p $GOPATH/src/github.com/decred/
$ git clone https://github.com/decred/dcrd $GOPATH/src/github.com/decred/dcrd
$ cd $GOPATH/src/github.com/decred/dcrd
$ godep ensure
```

is correct?

**Comment by vctt94** [comment]
Yeah, that's right. The documentation here is right https://github.com/decred/dcrd, you can check in case any doubts.

**Comment by brandonblock** [comment]
Cool, PR for this issue is ready
