### ISSUE TITLE
Update PoW page with gominer guide

### ISSUE THREAD

**Issue by gratefulcheddar** [decred/dcrdocs#41]
Update PoW page with gominer guide

**Comment by gratefulcheddar** [comment]
I've tasked myself to this.

**Comment by gratefulcheddar** [comment]
Note: Ubuntu 14.04 required for AMD cards GCN 1st generation or earlier

**Comment by gratefulcheddar** [comment]
Note: Ubuntu 14.04 required for AMD cards GCN 1st generation or earlier

**Comment by gratefulcheddar** [comment]
Having difficulty with drivers on Ubuntu 14.04 for my HD7870... don't see myself being able to do write a gominer Linux guide anytime soon.

**Comment by jholdstock** [comment]
I think this can be closed now @gratefulcheddar?

https://docs.decred.org/mining/proof-of-work/ contains a link to the gominer tutorial, and the tutorial itself looks pretty good

**Comment by jcvernaleo** [comment]
Agreed, we already cover gominer pretty well.
