### ISSUE TITLE
chinese fans want to help translate dcrdocs

### ISSUE THREAD

**Issue by detailyang** [decred/dcrdocs#412]
Hello. 

I'm a decred chinese fans and want to translation this project at [https://www.transifex.com/decred/dcrdocs/](https://www.transifex.com/decred/dcrdocs/).

Does anyone can help me?

**Comment by jholdstock** [comment]
Hi @detailyang,

Great to hear you are interested! The best place for translation support would be either the Decred Slack channel or IRC. You can find links at the bottom of the decred homepage https://decred.org/. Once you get in, you will want to speak to either user `jz` or user `ingsoc`

Good luck!

@dajohi can we close this issue please.

**Comment by detailyang** [comment]
@jholdstock Gotcha, Thanks to reply. I will contact your guys on slack:)
