### ISSUE TITLE
dcrdocs v0.0.2 navigation: show clearly on which sub-page you are

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrdocs#422]
Show more clearly on which sub-page the user is located. In the picture below, the user is in the "How To Vote" section. However, in the left sub-menu the "Getting Started" link is made bold. It'd be more logical to make the "How To Vote" bold in the left navigation menu, to let the user know where he is located.

![image](https://user-images.githubusercontent.com/16287891/33837291-27af6880-de8c-11e7-8781-505d545b2619.png)

**Comment by jholdstock** [comment]
It appears that the active menu link gets a unique css class added to it (`md-nav__link--active`), but there isn't any style associated with the class. Adding some css should be the only thing required to fix this.

But I do wonder if we might prefer the alternative menu the theme provides. There's a preview of that here: http://dcrdocs.jamieholdstock.com/
