### ISSUE TITLE
Cannot use top navigation without javascript

### ISSUE THREAD

**Issue by xaur** [decred/dcrdocs#423]
After the upgrade to new theme the nav links at the top is unclickable until I enable javascript.

Also, while removing left sidebar improves space utilization, it also removes an 'index' listing all articles.

Related #43

**Comment by jholdstock** [comment]
I think #425 will fix this - I've tested on my machine and it seems to work nicely without javascript. We can probably close #43 as well if #425 gets merged, I don't think there is any other critical javascript in the new theme

**Comment by jholdstock** [comment]
To clarify - MathJax does require js in order to render complex mathematical formula, but 99% of the site can be used without MathJax and so I don't deem it "critical"

**Comment by xaur** [comment]
Great that you test in no-js mode! I no longer feel alone.

#425 is merged, I confirm the problem is solved now.

Interestingly, this is the first ever content show/hide mechanism I encounter that works without javascript. I saw CSS animations earlier and the Reddit's "you have new messages popup", but those were not user-triggered. I have no idea how it is possible and it actually looks scary -- my first thought was my javascript is not disabled when I think it is :)

**Comment by jholdstock** [comment]
> Interestingly, this is the first ever content show/hide mechanism I encounter that works without javascript.

Me too. It's quite a smart solution - we can thank the material theme for mkdocs for providing that nice touch.

@dajohi  we can close this issue now.

**Comment by jholdstock** [comment]
@jolan @dajohi  this one can be closed.

**Comment by jolan** [comment]
Closed via #425.
