### ISSUE TITLE
Add a "recreate wallet" troubleshoot section for decrediton

### ISSUE THREAD

**Issue by matheusd** [decred/dcrdocs#430]
It's somewhat common to ask users to re-create a wallet from seed in decrediton. We should have a page/subsection in troubleshooting to describing the detailed steps of doing that safely.

**Comment by jholdstock** [comment]
This already exists in the docs:
https://docs.decred.org/getting-started/user-guides/decrediton-setup/#restore-existing-wallet-from-seed

So I think this issue can be closed

**Comment by matheusd** [comment]
I meant this more as a procedure on how to find and delete the existing wallet file. But users can now do that inside decrediton, so I agree this can be closed.
