### ISSUE TITLE
add more developer/advanced user/technical information

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#431]
_@dnldd on Slack..._ 
> any plan on adding  https://github.com/decred/dcrd/tree/master/docs to the updated decred docs? https://github.com/decred/dcrd/blob/master/docs/json_rpc_api.md might be tricky considering the layout, thoughts?

**Comment by jholdstock** [comment]
I feel like this level of documentation should actually stay in the respective github repo personally.

In my mind, `dcrdocs` should be the entry point for anybody wanting to learn about Decred - whether they are a researcher, investor, developer or even a complete blockchain/Decred newbie.The level of documentation in the `dcrd` repo is targeted at small subset of that total `dcrdocs` audience (mainly devs), and I feel that some clear links from `dcrdocs` into the `dcrd` repo would be adequate.  This actually feeds into a re-vamp of the "Contributors" section which I have been considering for a while.

Anybody technical enough to want to go through the `dcrd` docs is probably comfortable reading them on github.

A further thing which comes to mind is that the maintainers of `dcrdocs` and `dcrd` docs are probably different people - `dcrd` devs may not want to start having to keep `dcrdocs` updated.

All of that being said - I really like the look of the `dcrd` docs, they're concise and well written. They could definitely inspire a refresh of the existing guides on `dcrdocs`

**Comment by xaur** [comment]
In several projects this is solved by having a brief top level section in the documentation called "Developers" or "For developers", which is a top entry point for developers/contributors. The "Contributing" section in #435 seems on topic, although having the word "developers" would take 1-2 seconds less to catch my eye.

**Comment by jolan** [comment]
I go back and forth on this myself.  On one hand, it would be nice to have some sort of general on-boarding material for interested devs or advanced/technical users so they have a good jumping off point.

On the other hand, the docs should remain focused on the common user and the model so far for aspiring/new developers is to tell them to be pro-active and find some problem/issue that they care enough to fix.

There were a lot of overlapping issues about adding more technical details to the documentation like testnet, compiling from source, and listing various blockchain parameters which can be added if it can be determined how we want to integrate it.

**Comment by dnldd** [comment]
The technical docu of dcrd could benefit a lot from the presentation of dcrdocs, would make it easier to peruse. I'd gladly help update dcrdocs if a sub-section is created for technical dcrd docu.

**Comment by jholdstock** [comment]
Doesnt seem like this isnt going ahead, but we do now have https://github.com/decred/dcrdevdocs (https://devdocs.decred.org)
