### ISSUE TITLE
document politeia, proposal lifecycle, and governance

### ISSUE THREAD

**Issue by jolan** [decred/dcrdocs#442]
Opening as a catch-all to replace #258 and #268 from the survey results.

**Comment by davecgh** [comment]
I discussed this a bit on reddit [here](https://www.reddit.com/r/decred/comments/7jwj65/will_politeia_replace_decred_change_proposals/dr9qgsb/).

**Comment by s-ben** [comment]
Just going through open PRs here, and this one looks like it's already been addressed. Close?

**Comment by jholdstock** [comment]
Agreed. Closing
