### ISSUE TITLE
Implement Decred icon set

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdocs#450]
![1 csykrqr3brn7dngp2u8kga-3](https://user-images.githubusercontent.com/17774057/34751025-e64626a2-f5b2-11e7-9e22-63ef08031087.png)

The current documentation icons should be changed to DCR icons. I've complied a list of the icons what we have at the moment and where they can be used. Most are covered, and those with the tag `none` should be just left without an icon.

Icons: [dcr - docs icons - 012018.zip](https://github.com/decred/dcrdocs/files/1617178/dcr.-.docs.icons.-.012018.zip)

What Is Decred `keep as it is - DCR symbol`
What is a cryptocurrency? `Cryptocurrency.svg`
What is the blockchain? `Blocks.svg`

**Getting Started**
Beginner’s Guide `Flag.svg`

Obtaining DCR `ObtainingDecred.svg`
- Purchasing Decred `PurchasingDCR.svg`
- Mine for Decred (PoW) `PoWMine.svg`
- Stake Mine for Decred / Proof-of-Stake (PoS) `TicketVoted.svg`
- Contribute to Decred `Credits.svg`
- Sell / Trade Goods or Services for Decred `SellGoods.svg`

Using the Block Explorer `BlockExplorer.svg`
- Overview `Info.svg`
- Blocks `Blocks.svg`
- Transactions `Transactions.svg`
- Ticket purchases `TicketLive.svg`
- Proof-of-stake votes` TicketVoted.svg`

Mainnet Voting `TicketVoted.svg`
- Introduction `none`
- Voting Preparation `none`
- Verifying Your Vote `none`
- Tracking Vote Progress `none`
- Voting Archive `none`
- Change PoS Staking Algorithm `none`
- Voting Results `none`
- Start Lightning Network Support `none`

How To Vote `TicketVoted.svg`
- Stakepool Voting `Pool.svg`
- Solo Voting `Solo.svg`

Using Testnet Guide `none`
- Why Use Testnet? `none`
- How to Run a Testnet Node `none`
- Decrediton `none`
- Command-Line Suite `none`
- Acquiring Testnet Coins `none`

Decred Constitution `Constitution.svg`
- Principles `none`
- Blockchain Governance `none`
- Project Governance `none`
- Funding `none`

**Wallets** 
Decrediton Setup Guide `Wallet.svg`
Using Decrediton `Wallet.svg`

CLI Installation guide `Dcrtl`

Web Client User Guide `Wallet.svg`
Create your web client wallet `CreateWallet.svg`
Send funds with the web client `Send.svg`
Receive funds with the web client `Receive.svg`

**Proof-of-Stake (PoS) Mining**
Proof-of-Stake (PoS) Mining `TicketVoted.svg`
How To Stake `QuestionTicket.svg`
Solo PoS `Solo.svg`
PoS using a Stakepool `Pool.svg`
PoS General FAQ `TicketLive.svg`
Solo Mining `Solo.svg`
Buying Tickets and Fees `BuyTicket.svg`
Voting Tickets `TicketVoted.svg`
Stake Pools `Pool.svg`

**Proof-of-Work Mining**
Proof-of-Work (PoW) Mining `PowMine.svg`
Overview `none`
Solo Mining or Pool Mining `none`
- (small icon) Solo Mining Solo.svg`
- (small icon) PoolMining `Pool.svg`

Obtain a Decred Address to Receive Funds With `Receive.svg`
Sign up for pool `SignUpForPool.svg`
GPU Drivers/Software `Servers.svg`
Select and Download Mining Software  `Download.svg`
Running the Software `Dcrtl.svg`

**FAQ**
General `Meta.svg`
Configuration `Config1.svg`
Wallets and Seeds `CreateWallet.svg`
- Sources `Sources.svg`

Web Client `Wallet.svg`
- Sources `Sources.svg`

Blocks `Blocks.svg`
- Sources `Sources.svg`
Errors and Common Problems `Question.svg`

**Advanced**
Manual CLI Install `Dcrtl.svg`
- macOS `none`
- Linux `none`
- Windows `none`
- Minimum Configuration `none`

Storing Login Details `Harddrive.svg`
-  Configuration File Basics `none`
- dcrd.conf `none`
- dcrwallet.conf `none`
- dcrctl.conf `none`
- Additional Configuration Options `none`

Program Options `Options2.svg`
Block Header Specifications `BlockHeader.svg`
- Block header format `none`
- Example encoded block header `none`
- Example encoded block header as raw bytes `none`
- Mining Details  `none`

Blockchain Parameters `Blocks.svg`
- Blockchain parameters `none`
- PoS network parameters `none`

Transaction Details `Transactions.svg`
- Transaction Format `none`
- Inputs `none`
- Outputs `none`
- Serialization `none`

Verifying Binaries `Code.svg`
Inflation `Rocket.svg`
Deleting Your Wallet `DeleteWallet.svg`
Advanced dcrctl Usage `Dcrtl.svg`
Simnet`Dcrtl.svg`

- Overview `Info.svg`
- Getting Started `AtoB.svg`

**Research**
Overview `Info.svg`
Hybrid Design `Code.svg`
Decentralized Stake Pooling `Pool.svg`
Elliptic Curve Signature Algorithms `Code.svg`
BLAKE-256 Hash Function `Code.svg`
Script Extensions `Code.svg`
Signature Script Isolation and Fraud Proofs `Code.svg`
Transaction Extensions `Code.svg`
Schnorr Signatures `Code.svg`
Miscellaneous Improvements `Code.svg`

**Contributing**
Contributor Compensation `ObtainingDCR.svg`
- Request for Proposals (RFP) `RFP.svg`
- Contractors `User.svg`
- - Becoming a Contractor `Introductions.svg`
- Sources `Sources.svg`

Contributor Projects `UserProjects.svg`
- Dashboards `none`
- Mobile Apps `none`
- Wallets `none`
- Proof of Stake `none`
- Command line `none`

Guidelines 
- Using Github` github logo`
- Source Code Contributions `Code.svg`

**About**
Support Directory `Chat.svg`
Credits `Credits.svg`
License `Document.svg`

**Comment by jholdstock** [comment]
I'm going to pick this one up

**Comment by jholdstock** [comment]
Changes ready for review. Great work on the icons btw!
