### ISSUE TITLE
PoS Ticket Voting Distribution is Inaccurate

### ISSUE THREAD

**Issue by nitronick600** [decred/dcrdocs#489]
From a slack discussion with @davecgh about the PoS reward system outlined here: https://docs.decred.org/mining/proof-of-stake/

I'm not sure what the correct verbiage should be there, but we should display the CDF prominently. 

> NickH [3:24 PM]
> How many tickets do you think you need to average a vote a day?
> I guess since it’s a normal distribution, you can really only build a confidence interval.
> 
> davecgh [3:37 PM]
> 30
> 
> NickH [3:39 PM]
> How did you come up with that number? (edited)
> It’s not intuitive, by any means.
> 
> davecgh [3:40 PM]
> Did the math a while ago when it came up in trading.  However, the intuition is 28 days to vote on average + 512 blocks of maturity ~= 30 days.
> 
> Ergo if you want one a day on average and it's ~30 days all in on average, you need X/30 = 1 = 30
> The real math is obviously more involved, but that napkin math is close enough that it works out.
> 
> NickH [3:43 PM]
> I guessed 56ish
> after 28 days, only half your tickets have voted
> 
> davecgh [3:44 PM]
> That's not true though.
> 
> NickH [3:44 PM]
> right? it’s 50% chance of happening after 28 days
> say i stake 100 tickets today (i don’t have 100 tickets :slightly_smiling_face: )
> 28 days from now, on average, 50 of them will have voted.  Right? or nah
> 
> davecgh [3:45 PM]
> No, not sure where that got started to be honest.  Look at the CDF curve.  The halfway point is closer to 19 days iirc.
> Remember that there is a very long tail, so it skews the average over to 28 days, even though the 50% point is before that.
> 
> NickH [3:46 PM]
> ah
> 
> raedah [3:46 PM]
> I dont think it got started anywhere in particular. Its just when people see "28 day average" they tend to think of it in terms of a even distribution, which its not.
> 
> NickH [3:47 PM]
> yeah i didn’t realize it’s a cdf not normal
> "The chance of a ticket voting is based on a Poisson distribution with a mean of 28 days. After 28 days a ticket has a 50% chance to have already voted."
> 
> davecgh [3:50 PM]
> Yeah, it's a completely independent probability for a ticket to be selected.  That statement is just wrong.
> Somebody put it in the docs I guess, but it's wrong.

## Edit

From later discussion: 

> davecgh [4:07 PM]
> Your probability of voting in the first block is 5/N, where N is number of tickets.  Since N = 40960 (that's the target pool size, though it does change, so it's impossible to 100% calculate the values exactly, it's close), that yields 5/40960 = 1/8192.  So, the probability that will vote in the 2nd block is the probability you did *not* vote in the first block times the probability you vote in the second.  Or, in math terms, that is (1 - 1/8192)*(1/8192).  Ergo, if you want to know what the probability of having voted *by* the second block, you have to sum each independent probability.  In this case, that would be (1/8192) + (1 - 1/8192)*(1/8192).
> 
> Now, just carry that out until expiration, and you've built a curve, which clearly shows it's not an even distribution.

**Comment by davecgh** [comment]
To confirm, 19.5 days is ~50.16% chance of having voted.  So, if the docs are going to make an claims about 50%, that would be the correct value.

That said, I don't thinks the docs should be making a claim like that anyways, since it isn't particularly useful given it's not a normal distribution.  What I would suggest instead is showing a nice graph with days plotted against the probability to have voted by that many days, as it will much more clearly show the proper distribution.

**Comment by chappjc** [comment]
For some discussion about the distributions, please see https://github.com/decred/dcrdata/pull/361#issuecomment-372167721

Also:

https://github.com/decred/dcrdata/blob/e22ff164f2e24e11c2b2fecd712821d008db7a43/explorer/explorerroutes.go#L257-L267

Histogram of ticket spend times (including exires) from actual blockchain data:

![image](https://user-images.githubusercontent.com/9373513/40150832-e2dfadd0-5930-11e8-8e45-ac868ee24b74.png)

Not including expires (just lottery winners):

![image](https://user-images.githubusercontent.com/9373513/40150846-f043c22c-5930-11e8-8546-831019ff8232.png)

**Comment by davecgh** [comment]
For reference, here is the equation to calculate the probability of voting by block `B`:

![image](https://user-images.githubusercontent.com/2115102/40152038-183fb2dc-5949-11e8-9b08-44795918eda3.png)

**Comment by davecgh** [comment]
More details I wrote in slack.  Obviously most of this doesn't need to make it into the docs, but putting it here so the documentation folks can pick and choose what's necessary.

> Thus, the probability of voting in the first block is 8191^0/8192^1 = 1/8192 ~= 0.00012 ~= .012%.  The second is that (1/8192) + 8191^1/8192^2 ~= 0.000244 ~= .024%, and so on.
>
> However, as I hinted at earlier, you can do the calculation a lot more efficiently by realizing it's a Poisson process with a mean of 8102, as described earlier, and applying the exponential CDF to it.  e.g  `1-e^-(λt)`.  Where λ is the same as B, the number of blocks, and t is 1/8102.
>
> For example, using that with the same 1 and 2 blocks:
>
> 1-e^-(1/8102) ~= 0.00012 ~= 0.012%
>1-e^-(2/8102) ~= 0.00024 ~= 0.024%
>
>Some other interesting ones:
>
> 10 days (~2880 blocks) ~= 29.92%
> 19.5 days (~5616 blocks) ~= 50%
> 28 days (~8064 block) ~= 63.04%
> 60 days (~17280 blocks) ~= ~88.15%
> 40960 blocks (last possible block before expiration) ~= 99.4%
>
> Again, these are all ideal, because the pool size is almost never perfectly 40960, nor does every block always have 5 votes.  Nevertheless, you'll notice empirical data from the chain lines up nearly perfectly.
