### ISSUE TITLE
Remove external js/css dependancies

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrdocs#49]
There are two bits of js and css that are loaded externally.  Those should be moved into the repo and self-hosted.

**Comment by jcvernaleo** [comment]
With #50 in, only MathJax remains not local.  That one seems a big harder to do locally though.

**Comment by jholdstock** [comment]
I spent some time looking at this. The difficulty in moving MathJax to be hosted alongside the rest of the docs is that the server software used by dcrdocs (tornado) attempts to insert a `livereload.js` script into the MathJax files.

This can be recreated by attempting to host the file `MathJax/extensions/MathMenu.js` in tornado server. This file contains the string "</title>" and this is the point where tornado attempts to insert `livereload.js`

**Comment by jcvernaleo** [comment]
So it sounds to me like this is something we have to close and mark as 'won't fix' since I do not see us wanting to get into hacking tornado.

**Comment by jcvernaleo** [comment]
@jholdstock Are you ready to accept defeat on this one like I did? :)

If so I'd like to close it.

**Comment by jholdstock** [comment]
Sure - go ahead and shut it down

**Comment by jcvernaleo** [comment]
Since @jolan, me, and @jholdstock have all tried (very little alphabetic diversity there :) ) and each decided this can't be done in a useful manner, closing this issue.
