### ISSUE TITLE
Rewrite to make use of new terminology

### ISSUE THREAD

**Issue by Arriu** [decred/dcrdocs#504]
The Docs need a rewrite to consistently make use of "(PoS) Voting / Voter / Voting Service Provider" instead of "(PoS) mining / Staking / Staker / Stakepool"

**Comment by xaur** [comment]
Related: https://old.reddit.com/r/decred/comments/95r578/proposed_changes_to_decred_jargon/

**Comment by jholdstock** [comment]
Going to close this issue as the work is already being tracked in #581 and #582.
