### ISSUE TITLE
Outdated link to dcrd repo in Program Options section

### ISSUE THREAD

**Issue by hypernoob** [decred/dcrdocs#530]
https://github.com/decred/dcrdocs/blame/8f29183392f6ef07e5e98990d995c11e24545564/docs/advanced/program-options.md#L156

This should be replaced by a footnote that links to the [new sdiff algorithm](https://github.com/decred/dcps/blob/master/dcp-0001/dcp-0001.mediawiki).

**Comment by jholdstock** [comment]
Hey @hypernoob. I'm currently working in revamping this section as part of #367 so you can leave this one with me
