### ISSUE TITLE
CoinbaseMaturity should not be historic.

### ISSUE THREAD

**Issue by hypernoob** [decred/dcrdocs#531]
https://github.com/decred/dcrdocs/blame/master/docs/advanced/blockchain-parameters.md#L25

**Comment by jholdstock** [comment]
> CoinbaseMaturity should not be historic.

Why not? 

I noticed that we also have two more items marked as historic: https://github.com/decred/dcrdocs/blame/master/docs/advanced/blockchain-parameters.md#L32-L33

**Comment by hypernoob** [comment]
CoinbaseMaturity still [applies](https://github.com/decred/dcrd/blob/d7135098cf3eed2c08c2a51f30aa3f4c2d6361c0/blockchain/validate.go#L1679).
