### ISSUE TITLE
Blocksize in blockchain parameters

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#533]
@gozart1 suggests that blocksize should be added to https://docs.decred.org/advanced/blockchain-parameters/#blockchain-parameters_1

**Comment by hypernoob** [comment]
Can I help with this?

**Comment by jholdstock** [comment]
Go for it.

**Comment by zhizhongzhiwai** [comment]
@jholdstock  

Maximum block size | 393,216 | The maximum size of a block in bytes.

~ 393,216(0.38k) maximum block size, is it wrong??
