### ISSUE TITLE
Add a section about Decred nodes

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrdocs#534]
It would be great to have a definitive guide on how to successfully run a Decred node (one that benefits the network and does not require expensive mining hardware).

**Comment by s-ben** [comment]
@noahpierau , I'll be setting up a Decred node here in the next few days. I'm on a 2015 MacBook Pro, and was going to start there. Also have projects running on AWS and Google Cloud, and would be interested playing around with SBCs (Rasberri Pi, etc.) if that's a thing (still very new to project). I also have a technical writer background, and am looking for technical writing tasks actually as a way I can help out. If anyone has resources they can point me to around this issue (archived slack discussions about this, blogs, etc.), would be interested in those as well.

**Comment by noahpierau** [comment]
issue can be closed, we have a page now: https://docs.decred.org/advanced/full-node/
