### ISSUE TITLE
Replace links to (mainnet.decred.org) with (explorer.dcrdata.org)

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrdocs#535]
As per @jholdstock's comment 

> In agenda-voting.md we have

`The easiest method to track your how your tickets actually voted is to use the [block explorer](https://mainnet.decred.org) to view each of your votes.`

> In dcrd-setup.md we have the following sentence:

`... the last block processed against the last block height on [the official block explorer](https://mainnet.decred.org/). `

There might be more of these links in the docs, ideally we replace all of them with a link to dcrdata.

**Comment by hypernoob** [comment]
Can I work on this?

**Comment by jholdstock** [comment]
Sure
