### ISSUE TITLE
Link to dcrdata for blockchain size

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#546]
In the decrediton user guide, we advise that downloading the whole blockchain is required to run decrediton. 

From the page https://docs.decred.org/getting-started/user-guides/decrediton-setup/

> At the end of May 2018 the Decred blockchain was 3.3GB.

This PR for dcrdata adds a chart showing the current blockchain size: https://github.com/decred/dcrdata/pull/463

Once this change is live on https://dcrdata.org, we can link to it from the docs to provide a more accurate and up-to-date figure

**Comment by noahpierau** [comment]
Started working on this issue, expect a PR soon!

**Comment by noahpierau** [comment]
According to https://alpha.dcrdata.org/charts the blockchain size today is <2.4G

Did the changes to the blockchain database have this much effect on the file size?

**Comment by noahpierau** [comment]
Preliminary changes: https://github.com/noahpierau/dcrdocs/blob/master/docs/getting-started/user-guides/decrediton-setup.md
