### ISSUE TITLE
Change Header1 font and color

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/dcrdocs#556]
Replace Helvetica font of **Header1** type of text with **Source Sans Pro Regular** 34px #596D81
(what kind of headers I mean is on the screen below)

![image](https://user-images.githubusercontent.com/8841018/43718691-0c9493ea-9994-11e8-9c25-2b911ad0c186.png) 
![image](https://user-images.githubusercontent.com/8841018/43719946-d297352c-9997-11e8-8ee1-482b8d08fa25.png)

The folder with new font: 
[Source_Sans_Pro.zip](https://github.com/decred/dcrdocs/files/2262713/Source_Sans_Pro.zip)

**Comment by jholdstock** [comment]
In progress
