### ISSUE TITLE
Change bold body text font and color

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/dcrdocs#559]
Replace bold body text font and color with **Source Sans Pro Semibold** 16 px #48566E
(kind of text I'm talking about)
![image](https://user-images.githubusercontent.com/8841018/43721963-e1c0461a-999c-11e8-8fa7-c3c9ee9dc088.png)

The folder with new font:
[Source_Sans_Pro.zip](https://github.com/decred/dcrdocs/files/2262880/Source_Sans_Pro.zip)

**Comment by jholdstock** [comment]
In progress
