### ISSUE TITLE
Change the color of icon set

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/dcrdocs#561]
Change the color of icon set ( will provide with an example later)

**Comment by jholdstock** [comment]
Hi @MariaPleshkova, any update for this one?

**Comment by MariaPleshkova** [comment]
Hey @jholdstock 
Here's an updated set of icons 
[Updated dcrdoc icons.zip](https://github.com/decred/dcrdocs/files/2509939/Updated.dcrdoc.icons.zip)

**Comment by jholdstock** [comment]
Hi @MariaPleshkova ,

The current icon set provided in #450 by  @linnutee had unique descriptive names, whereas the icons in the new set are all named "Group-XX.svg".

The current icon set is [visible here](https://github.com/decred/dcrdocs/tree/master/docs/img/dcr-icons)

Could you possibly recreate the .zip with the same descriptive names as before?

Thanks

**Comment by MariaPleshkova** [comment]
Hi @jholdstock ,
Sure

Icons: [dcrdoc_updated icons.zip](https://github.com/decred/dcrdocs/files/2530066/dcrdoc_updated.icons.zip)


**Home**
What Is Decred  `DCRsymbol.svg`

**Getting Started**
Beginner’s Guide `Flag.svg`

Obtaining DCR `ObtainingDecred.svg`

- Overview `Info.svg`
- Purchasing Decred `PurchasingDCR.svg`
- Mine for Decred (PoW) `PoWMine.svg`
- Stake Mine for Decred / Proof-of-Stake (PoS) `TicketVoted.svg`
- Contribute to Decred` Credits.svg`
- Sell / Trade Goods or Services for Decred `SellGoods.svg`

Using the Block Explorer `BlockExplorer.svg`
- Overview `Info.svg`
- Blocks `Blocks.svg`
- Transactions `Transactions.svg`
- Ticket purchases `TicketLive.svg`
- Proof-of-stake votes `TicketVoted.svg`

**Governance**
Introduction to Decred governance `Governance.svg`
Mainnet Voting Guide `TicketVoted.svg`

How To Vote `TicketVoted.svg`
- Stakepool Voting `Pool.svg`
- Solo Voting `Solo.svg`

Politeia proposals and voting `Politeia.svg`

Decred Constitution `Constitution.svg`

**Wallets**
Decrediton Setup Guide `Wallet.svg`
Using Decrediton `Wallet.svg`
 
CLI Installation guide `Dcrtl.svg`
dcrd Setup Guide `AtoB.svg`
dcrwallet Setup Guide `AtoB.svg`
dcrctl Basics `Dctrl.svg`
Buying tickets with dcrwallet `BuyTicket.svg`
dcr and dcrwallet CLI Arguments `Options2.svg`
dcrctl RPC Commands `Dctrl.svg`

Web Client User Guide `Wallet.svg`
- Create your web client wallet `CreateWallet.svg`
- Send funds with the web client `Send.svg`
- Receive funds with the web client `Receive.svg`

**Proof-of-Stake Voting**
Proof-of-Stake (PoS) Mining `TicketVoted.svg`
How To Stake `QuestionTicket.svg`
- Solo PoS `Solo.svg`
- PoS using a Stakepool `Pool.svg`

PoS General FAQ `TicketLive.svg`
Solo Mining `Solo.svg`
- Sources `Sources.svg`
Buying Tickets and Fees `BuyTicket.svg`
- Sources `Sources.svg`
Voting Tickets `TicketVoted.svg`
- Sources `Sources.svg`
Stake Pools `Pool.svg`
- Sources `Sources.svg`

**Proof-of-Work Mining**
Proof-of-Work (PoW) Mining `PowMine.svg`
- Solo Mining or Pool Mining none
~~ (small icon) Solo Mining `Solo.svg`
~~(small icon) Pool Mining `Pool.svg`
- Obtain a Decred Address to Receive Funds With `Receive.svg`
- Sign up for pool `SignUpForPool.svg`
- GPU Drivers/Software `Servers.svg`
- Select and Download Mining Software `Download.svg`
- Running the Software `Dcrtl.svg`
 
gominer Pool Mining User Guide `PowMine.svg`
 
Proof of work mining `PowMine.svg`
- Sources `Sources.svg`

**FAQ**
General `Meta.svg`
- Sources `Sources.svg`

Configuration `Config1.svg`
- Sources `Sources.svg`

Wallets and Seeds `CreateWallet.svg`
- Sources `Sources.svg`

Web Client `Wallet.svg`
- Sources `Sources.svg`

Blocks `Blocks.svg`
- Sources `Sources.svg`

Common Errors and Solutions `Question.svg`

**Advanced**
Using Testnet Guide `Flag.svg`

Manual CLI Install `Dcrtl.svg`

Storing Login Details `Harddrive.svg`

Block Header Specifications `BlockHeader.svg`

Blockchain Parameters `Blocks.svg`

Transaction Details `Transactions.svg`

Verifying Binaries `Code.svg`

Inflation `Rocket.svg`
- Sources `Sources.svg`

Deleting Your Wallet `DeleteWallet.svg`

Simnet `Dcrtl.svg`
- Overview `Info.svg`
- Getting Started `AtoB.svg`

**Research**
Overview `Info.svg`

Hybrid Design `Code.svg`

Decentralized Stake Pooling `Pool.svg`

Elliptic Curve Signature Algorithms `Code.svg`

BLAKE-256 Hash Function `Code.svg`

Script Extensions `Code.svg`

Signature Script Isolation and Fraud Proofs `Code.svg`

Transaction Extensions `Code.svg`

Schnorr Signatures `Code.svg`

Miscellaneous Improvements `Code.svg`

**Contributing**
Contributor Compensation `ObtainingDecred.svg`
- Request for Proposals (RFP) `RFP.svg`
- Contractors `User.svg`
- Becoming a Contractor `Introductions.svg`
- Sources `Sources.svg`

Using Github `github logo`
Source Code Contributions `Code.svg`

**About**
Credits `Credits.svg`
License `Document.svg`
