### ISSUE TITLE
Change code-writing font

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/dcrdocs#562]
Replace code-writing font with **Source Code Pro Regular** 14px

The folder with new font:
[Source_Code_Pro.zip](https://github.com/decred/dcrdocs/files/2263070/Source_Code_Pro.zip)

**Comment by jholdstock** [comment]
I believe we should actually be using [Inconsolata](https://github.com/google/fonts/tree/master/ofl/inconsolata) for this, as per the branding guidelines at https://www.decred.org/brand/

**Comment by jholdstock** [comment]
Spoken with @linnutee -  Inconsolata is actually being phased out.

I will proceed to implementing this change
