### ISSUE TITLE
Add a vertical line next to the name of OS's and change the colour to green

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/dcrdocs#567]
There are also different OS in **Advanced->Manual CLI Installation** 
![image](https://user-images.githubusercontent.com/8841018/43845958-dc4c8b68-9b35-11e8-8017-f496c0be4488.png)
Add a vertical line left to the names of OS’s and change the colour to green (**#2ED8A3**)
(like in #566 )

**Comment by jholdstock** [comment]
Hi @MariaPleshkova,

I would actually like to suggest an alternative.

The following pages all have sections for Windows, MacOS and Linux:
- https://docs.decred.org/advanced/manual-cli-install/
- https://docs.decred.org/getting-started/user-guides/cli-installation/
- https://docs.decred.org/getting-started/user-guides/decrediton-setup/

I would like to wrap these in collapsible panels similar to the panels on this page: https://docs.decred.org/getting-started/dcrctl-rpc-commands/

This will reduce the amount of clutter on the screen, allowing the user to only expand the panel which is relevant for them.

What do you think?

**Comment by MariaPleshkova** [comment]
Hi @jholdstock, 
That's a good idea! 
And write there something like "click to expand the icntructions for Windows/Linux/etc."
