### ISSUE TITLE
Move blog to Git

### ISSUE THREAD

**Issue by xaur** [decred/dcrdocs#57]
[Decred](https://blog.decred.org/) and [Company 0](https://blog.companyzero.com/) blogs have some articles on Decred. I'd like to save them all locally.

Right now I use this:

```
wget \
    --timestamping \
    --recursive \
    --page-requisites \
    --convert-links \
    --accept html,png,jpg,txt \
    --reject-regex "/page/|/feed/|/tag/|/category/|/author/" \
    --wait=1 \
    https://blog.companyzero.com/
```

Obviously it is complex, slow, redundant, incomplete (if external images are linked), has no integrity protecteion and cannot be quickly synced to pull latest blogs.

Much cooler would be to just `git clone`.

Working examples of Git-based blogs:

* http://blog.ipfs.io/ ([source](https://github.com/ipfs/blog/))
* https://blog.invisiblethings.org/ ([source](https://github.com/rootkovska/rootkovska.github.io))

For more motivation see Joanna's [My New Git-based blog](https://blog.invisiblethings.org/2015/02/09/my-new-git-based-blog.html).

Sorry if this repository is a wrong place for this issue.

P.S. I wish the same for old Conformal blog, it had some articles on btcsuite.

**Comment by xaur** [comment]
Could be useful: Hugo, static site generator in Go ([website](http://gohugo.io/), [source](https://github.com/spf13/hugo))

**Comment by jcvernaleo** [comment]
I brought this up to the people who deal with the blog and there really isn't much interest in doing this as their current workflow works well and this would benefit very few people so it is unlike that this will happen.  Sorry.
