### ISSUE TITLE
Constitution: add notice about incomplete systems

### ISSUE THREAD

**Issue by xaur** [decred/dcrdocs#576]
Following recent [discussion](https://www.reddit.com/r/decred/comments/96j9ai/transparency_in_payments_made_with_the_community/e43btbt/) on Reddit I came to a realization that some people (and trolls) might mis-read the constitution as something that should have been fully in effect since day one. Obviously this is not possible because "Decred was not built in a day".

To prevent any confusion I suggest adding a notice on top of the page:

> Note: The constitution was written with the future in mind and has various portions that are contingent upon systems that are not yet complete.

While amendments to the constitution must happen with stakeholder approval, a notice on top is technically "outside" the document.

**Comment by RichardRed0x** [comment]
I like the idea, but I think the note will be stronger if it explains the process for getting to a proper binding constitution.

> Note: The constitution was written prior to Decred's launch, some portions of it are out-dated. Politeia will be used, when it launches, to propose amendments to the constitution for ratification by Voters.

**Comment by xaur** [comment]
Nice improvement.

I added the explainer bit about incomplete systems to make it clear that there is no intention to just remove the "uncomfortable" pieces with the next amendment. For instance, I expect the financial statements will appear, but perhaps not in the form and schedule as currently written. And this depends on systems and processes not yet implemented.

So there are two kinds of deviations between constitution text and present time I would like to cover: things that will stay but need more work to build, and things that may be removed because they are no longer relevant.

**Comment by RichardRed0x** [comment]
I tried to cover both of those concisely. I think they're pretty similar now because stakeholders can soon decide whether an item will stay with more work or some amendment or whether it's irrelevant. I can't think of much that is truly irrelevant, more shades of "not ready yet" to "will probably work a bit differently".
