### ISSUE TITLE
Jargon update: change dev fund to project treasury

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrdocs#582]
As part of the efforts to make Decred more appealing to the general public, we are updating our jargon.

Another proposed change that has broad consensus in the community is changing dev fund to project treasury. 

The rationale is explained here:
https://www.reddit.com/r/decred/comments/95r578/proposed_changes_to_decred_jargon/e3uv2yq

**Comment by RichardRed0x** [comment]
For this change, I think it could be worth some further discussion and/or voting on Politeia to nail it down, because I see support for [project/network][treasury/fund].

**Comment by justinsantoro** [comment]
Are we leaning more toward Decred Treasury or just Treasury for this now?

**Comment by RichardRed0x** [comment]
I would say any variation of [the/Decred/project] Treasury is fine if it makes sense in the context where it is used.

**Comment by dajohi** [comment]
the Decred Treasury
