### ISSUE TITLE
Update for Decrediton release 1.3.0

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#584]

**Comment by s-ben** [comment]
@jholdstock , can help with updating this if that would be helpful. Could update the screenshots and any command-line copy changes at least. Not sure if there are functional changes you need to document however, or if we're still waiting to remove the release candidate qualification, as we are on CLI release.

**Comment by jholdstock** [comment]
Please leave this one with me for now, I have some changes already and I will be finishing them when the proper release is done.

**Comment by dajohi** [comment]
1.3.1 now.
