### ISSUE TITLE
Change the screenshot of dropdown list

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/dcrdocs#588]
Replace this image ( https://docs.decred.org/getting-started/user-guides/how-to-vote/ ) 
![image](https://user-images.githubusercontent.com/8841018/44665640-18b4a480-aa1f-11e8-9d2d-1294cee62c17.png)
with this one 
<img width="711" alt="dropdown" src="https://user-images.githubusercontent.com/8841018/44665902-c4f68b00-aa1f-11e8-9be4-ae7eb98db4f4.png">

**Comment by s-ben** [comment]
P.S. To anyone looking to do this, I submitted a PR to fix this. Just realized I hadn't noted that in commit message.
