### ISSUE TITLE
Request: Glossary page 

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdocs#589]
Recommend creation of a glossary page that consists of short summaries of all the critical crypto and decred specific terms. When possible, each term can also link to specific docs entries for further read. 

A glossary page can essentially be used for a quick point of reference, as well builds a bit more consistency and be of help with localisation work. 

Few references:
https://crushcrypto.com/glossary/
https://www.upfolio.com/glossary

**Comment by jholdstock** [comment]
A nice resource we could possibly use as inspiration for our glossary:

https://www.fidelitydigitalassets.com/digital-asset-basics

**Comment by RichardRed0x** [comment]
I have prepared a [rough draft of a glossary](https://github.com/RichardRed0x/dcrwords/blob/master/README.md), it contains a list of terms and an initial attempt at a definition for many of these. It is more Decred-oriented than the linked examples, which are quite general. Our glossary could become quite general too, but I felt it was better to start with a focus on Decred-specific terms.

At this stage I'm looking for general feedback.
* Are the definitions too short?
* Are links to the relevant pages for more information (usually on docs) a good idea?
* How should this be organized? It is currently arranged very loosely around themes (e.g. general blockchain terns, PoS, PoW). Is alphabetical better?
* What state of maturity should this reach before moving to a page on dcrdocs?

**Comment by s-ben** [comment]
@RichardRed0x , Looks like a good start.

> Are the definitions too short?

Generally look OK. However, would need to determine on a case-by-case basis. If I go in and do a polish pass, would likely lengthen a little here, shorten a little there. 

> Are links to the relevant pages for more information (usually on docs) a good idea?

I see outbound links on two of three example glossaries posted on this thread. I think they're fine. 

> How should this be organized? It is currently arranged very loosely around themes (e.g. general blockchain terns, PoS, PoW). Is alphabetical better?

I would vote for alphabetical. It's the main convention for glossaries, and it might confuse readers to deviate from that. The main concern IMO is that it's easily searchable. A straight list is searchable by browser text search. We could also group into letters (A-E, F-J, etc.), as some glossaries do. Also, presumably we're going to link to term definitions occasionally from dcrdocs or other places (or other people will), so there's discoverability from there too. 

> What state of maturity should this reach before moving to a page on dcrdocs?

I'd say we're close to an "MVP". Ship it! Jk, we should at least do a proofing/polishing pass and fill out some of the empty definitions. I'm OK with leaving it heavily Decred-specific, possibly leaving out some general blockchain terms. There are tons of definitions for general blockchain terms one click away on Google. We could also just reuse some good open source definitions (e.g. Bitcoin.org's [Developer Docs](https://bitcoin.org/en/developer-documentation) have some good definitions of general blockchain terms, which are under MIT license; presumably to use those we'd just need to paste the license recognizing the source, if that's not awkward. We can also wordsmith some of the better definitions to make them our own. 

I think all of these terms are useful enough to be in the glossary. We might want to filter a little, so we just have the most basic general blockchain terms and Decred-specific terms. However I don't have a strong opinion. Would be up to do a proofing/polishing pass and fill in some definitions if you want to assign me some of them.

**Comment by RichardRed0x** [comment]
My reason for grouping by theme is that I think it should all be one page (and thus easily browser-searchable), I don't see what's to be gained from alphabetical listing. If someone is going to read through the page it's better for it to be organized by theme, if they're looking for a term definition they use search.

You're welcome to take a run-through now @s-ben, add missing terms and polish whatever you like. Let me know when you're done and I will do another pass myself, then maybe it's ready for dcrdocs.
