### ISSUE TITLE
Add pre-mine information to dcrdocs

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#59]
Information found in this forum post (amongst many others): 
https://forum.decred.org/threads/the-projects-commitment.730/

Would be nice to see the size of the dev pre-mine, c0 pre0mine, why the pre-mine was split that way. Also an explanation of the restrictions on devs/c0 selling/staking their pre-mine.

**Comment by gratefulcheddar** [comment]
Information about the dev subsidy should probably be on the same page as the premine info.

https://bitcointalk.org/index.php?topic=1290358.msg13412287#msg13412287

https://mainnet.decred.org/address/Dcur2mcGjmENx4DhNqDctW5wJCVyT3Qeqkx

**Comment by jholdstock** [comment]
Most of the info described above is included in the docs now but not the commitment to lock up the dev/c0 DCR for 1/2 years.
