### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#592]
@s-ben noted in #591 that the image `voting.png` on page `how-to-vote.md` is missing.

**Comment by s-ben** [comment]
Happy to fix this if someone can upload the screenshot here, or tell me where to take said screenshot.

**Comment by jholdstock** [comment]
Hi @s-ben,

Here is a screenshot from decrediton 1.3.0-rc1 which can be used for this.

![voting](https://user-images.githubusercontent.com/6762864/45025116-8588f980-b032-11e8-8eb2-17378859acd6.png)
