### ISSUE TITLE
Updating the Blockchain parameters

### ISSUE THREAD

**Issue by dmigwi** [decred/dcrdocs#608]
After my research I realised that the maximum size of block allowed in decred is **1MB** while the maximum size of a transaction allowed is **393,216 bytes**.

Currently what is available of the documentation in https://docs.decred.org/advanced/blockchain-parameters/ says otherwise..
<img width="571" alt="screen shot 2018-09-11 at 06 47 55" src="https://user-images.githubusercontent.com/22055953/45337105-1c076e80-b58f-11e8-85ca-0575452d06a7.png">

**Comment by dmigwi** [comment]
@davecgh 👆 Is the above accurate?

**Comment by davecgh** [comment]
The documentation is correct.  As @hypernoob linked to, the maximum size for a block on `mainnet` is indeed 393216.  [1000000 bytes](https://github.com/decred/dcrd/blob/566bb6625b83738cb97ab826d5d77e862d44e92c/wire/msgblock.go#L28) is maximum size the message on the wire is allowed to be.
