### ISSUE TITLE
Update stated Go version on https://docs.decred.org/advanced/contributing/

### ISSUE THREAD

**Issue by PrimeDominus** [decred/dcrdocs#611]
As per my discussion with @davecgh on the DCR Documentation channel today this should state Go1.10 instead of Go1.6 as it is presently. Since Decred runs on N and N-1 releases of Go. The most recent release of Go is 1.11, so that would mean things must be Go1.10 compliant.

Also, potentially a separate issue, yet maybe worth discussing: The wording of this could potentially be changed to state relative version numbers, similar to https://github.com/decred/dcrd/pull/1451 so that we don't have to keep updating this page with each new version of Go that is released. 

e.g. Instead of:

For projects using Go, you can follow this procedure. dcrd will be used as the example. This assumes you already have go1.6 or newer installed and a working `$GOPATH`.

We could have:

For projects using Go, ensure you have the latest Go release or the one prior (i.e. for compliance) installed and a working `$GOPATH`. Below is an example procedure for [dcrd](https://github.com/decred/dcrd).

While the example code block below the statement may need updating one day in the future if/when newer commands are required for newer releases of Go, at least Go release numbers won't need to be updated in the preceding text so frequently.

This all may seem trivial, yet I myself have been preparing to contribute Go code, and since there were different Go release versions stated in https://docs.decred.org/advanced/contributing/ and https://github.com/decred/dcrd/blob/master/docs/code_contribution_guidelines.md I felt it prudent to ask someone in chat first to confirm what is actually required. Having these docs worded in a way that is both clear and future-proof may be helpful.

**Comment by PrimeDominus** [comment]
Or maybe a better way to word it could be the following, this time also breaking it up into two paragraphs:

For projects using Go, ensure you have either the latest Go release or the one prior installed and a working `$GOPATH`. All Go code for Decred runs on N and N-1 releases of Go, and all Go code changes must be compliant for both.

Below is an example procedure for [dcrd](https://github.com/decred/dcrd).

**Comment by s-ben** [comment]
Hey @PrimeDominus , @dajohi , it looks like the PR that implements this was merged and closed in #612?
https://github.com/decred/dcrdocs/pull/612

If so we should close. 

P.S. In case you didn't know (I didn't until a few days ago), if you put "Closes #ISSUE_NUMBER" in the PR comment, it will automatically close Issue #ISSUE_NUMBER when the PR is merged.

**Comment by PrimeDominus** [comment]
@s-ben Ah, you're right! Thanks for the heads-up. I'll keep this in mind :)
