### ISSUE TITLE
travis: catch build failure within docker

### ISSUE THREAD

**Issue by dajohi** [decred/dcrdocs#637]
Right now, docker build returns 0 even if the mkdocs script fails, thus tricking Travis into thinking the build passed.

**Comment by jholdstock** [comment]
I am not able to recreate this.

I am running `./build_docker.sh` with the following changes:
- Make `mkdocs.yml` invalid by adding some random text to make `mkdocs build` fail
- Add `exit 1` to `build_docs.sh`
- Make `Dockerfile` invalid by adding random text

In every case, `build_docker.sh` fails with exit code 1.

**Comment by dajohi** [comment]
```
Successfully installed Pygments-2.2.0 fontawesome-markdown-0.2.6 mkdocs-material-3.0.4 pymdown-extensions-6.0
 ---> 8f643e136adf
Removing intermediate container f659b15a5ae1
Step 9/14 : RUN ./build_docs.sh && chmod -R a+rw site
 ---> Running in b095684cc420

=========================================
  Building dcrdocs into directory site/  
=========================================

INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /root/site 
WARNING -  Documentation file 'mining/proof-of-work.md' contains a link to 'mining/beepool.org' which is not found in documentation files. 

Exited with 1 warnings in strict mode.
The command '/bin/sh -c ./build_docs.sh && chmod -R a+rw site' returned a non-zero code: 1

===================
  Build complete
===================

You can now run dcrdocs with the following command:
    docker run -d --rm -p <local port>:80 decred/dcrdocs:latest
 
dhill@docker:~/git/dcrdocs$ echo $?
0
```

**Comment by jholdstock** [comment]
I have attempted to recreate this by inserting an invalid link into a `.md` file and I see the same error message posted above, but my script fails as expected.

I think this may be an environmental issue. What shall is being used here, and how is the `build_docker.sh` script being invoked?

**Comment by jholdstock** [comment]
Looking further, it seems like this issue does not actually affect travis.

Checking the commit history on master: https://github.com/decred/dcrdocs/commits/master
We can see that #633 was merged on the 12th October and the Travis build failed.

https://travis-ci.org/decred/dcrdocs/builds/440825153
The log shows that the build failed exactly as expected, with the same error message posted above

**Comment by jholdstock** [comment]
Any further info @dajohi ? Did you manage to recreate this?

**Comment by dajohi** [comment]
Uninterested :)
