### ISSUE TITLE
Keyboard navigation for search box

### ISSUE THREAD

**Issue by gozart1** [decred/dcrdocs#64]
The first thing I want to do after typing something in the search box and finding useful results is to hit down arrow or enter to navigate to a selection.

Would anyone else find it useful if I added that?

**Comment by gozart1** [comment]
the proposed spec would be:

- First search result is auto-highlighted every time search results change
- Pressing Enter key to navigates browser to url of highlighted search result
- Pressing Up or Down arrow keys highlights the next/prev search result

**Comment by jcvernaleo** [comment]
I'm always in favor of more keyboard navigation.

**Comment by jolan** [comment]
Seems to be present in the current theme, closing.
