### ISSUE TITLE
Icons for newly added pages

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#661]
Hi @MariaPleshkova, 

Further to the work completed by @linnutee in #450, could you please suggest icons to accompany page headers on the newly added pages:

https://docs.decred.org/governance/governance/
https://docs.decred.org/governance/politeia/

Thanks

**Comment by MariaPleshkova** [comment]
Added these icons tho the archive in here #561 

Introduction to Decred governance `Governance.svg`
Politeia proposals and voting `Politeia.svg`
