### ISSUE TITLE
Possible typo on "Mainnet Voting Guide"

### ISSUE THREAD

**Issue by szpasztor** [decred/dcrdocs#669]
The intro section on the [Mainnet Voting Guide](https://docs.decred.org/getting-started/user-guides/agenda-voting/#introduction) page mentions "Stake Version Interval" multiple times. However, the corresponding diagram (titled "Voting Cycle") seems to have a typo in one of the labels at the top: 
`A single Stale Version Interval = 2016 Blocks ~1 week` instead of 
`A single Stake Version Interval = 2016 Blocks ~1 week`

**Comment by s-ben** [comment]
@karamble , was this your diagram?

**Comment by jholdstock** [comment]
@mariapleshkova produced this diagram for #642.

Any chance of producing a new version with the correction Maria?

Is the source file for this image already in GitHub somewhere? I couldn't find it anywhere on https://github.com/decred/dcrdesign/releases. Perhaps we could add it to this repo if not - it would make this kind of issue easier to fix in the future without having to depend on a single person to be available.

**Comment by MariaPleshkova** [comment]
@jholdstock added changed diagram to #642
