### ISSUE TITLE
Link on the web wallet page goes nowhere

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#688]
https://docs.decred.org/getting-started/user-guides/web

Under heading "Create your web client wallet", "Step 4".

There is a link "FAQ" which goes nowhere

**Comment by s-ben** [comment]
Right, just links to the current page (inception link). I would guess it's supposed to link to,
https://docs.decred.org/faq/wallets-and-seeds/

However, I just skimmed this page, and didn't see anything explicitly saying don't do what the link is pointing to, `Only use ONE wallet at a time with a given seed `.

**Comment by dajohi** [comment]
all references to web wallet should be removed.

**Comment by s-ben** [comment]
@dajohi , creating Issue now. Any specific reason I can put in the description?

**Comment by jholdstock** [comment]
The web wallet was put online for airdrop recipients when the only other available wallet was `dcrwallet` via CLI. It is not a very user friendly wallet, it is made practically redundant by Decrediton (especially with SPV mode). It is a point of centralisation which requires the user to trust a remote server which is not under their own control. The code is a nightmare. There is time/cost associated with running the web wallet. 

This list goes on... :)

**Comment by jzbz** [comment]
Web wallet is deprecated and will be take off-line soon, all mentions of it should be removed.
