### ISSUE TITLE
Remove references to web wallet

### ISSUE THREAD

**Issue by s-ben** [decred/dcrdocs#694]
Per discussion on Issue #688 , there is an opinion that references to the web wallet should be removed. Does anyone want to keep the web wallet?

Comments:

@dajohi 

> all references to web wallet should be removed.

@jholdstock 
> The web wallet was put online for airdrop recipients when the only other available wallet was dcrwallet via CLI. It is not a very user friendly wallet, it is made practically redundant by Decrediton (especially with SPV mode). It is a point of centralisation which requires the user to trust a remote server which is not under their own control. The code is a nightmare. There is time/cost associated with running the web wallet.

**Comment by jzbz** [comment]
Heh I just commented on that:
https://github.com/decred/dcrdocs/issues/688#issuecomment-437646449

**Comment by s-ben** [comment]
Great, solves that :) Will create a PR.
