### ISSUE TITLE
Handle 404 properly

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#696]
https://docs.decred.org/not-real

httpd is current returning its own stock 404 page which is kinda nasty. Need to explore some alternatives here - maybe redirect to the home page, maybe implement our own 404 page.

**Comment by jholdstock** [comment]
The same issue for decred.org:
decred/dcrweb#418

**Comment by s-ben** [comment]
+1 own 404 page. Redirect back to home is just confusing
