### ISSUE TITLE
Add Signature and Receipt details to Politeia data page

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#697]
#679 introduced the page "Navigating Politeia Data".

@s-ben noticed that there are some extra details which can be added. He explained in this comment: 
>Also, while using this page to understand Pi data for my script (it's already being used!), I ran across a need to understand the 'signature' and 'receipt' fields in the 'ballot.journal' files. Looking at comments in the /politeia code, I guessed at the definitions below, which were verified as accurate by @lukebp in the #politeia channel. I figure we can put these in along with my polishing edits after merge. Not sure if we want to put this much technical detail into these definitions though, or keep them higher level more like the other definitions.
>
> **Signature**: signature of the vote, which is created using the voter's private key. This can be used to verify the proposal voted on, the ticket that voted, and the vote choice.
>
> **Receipt**: The Politeia server signature of the vote signature. This can be used to verify that the vote was signed (verified) by the Politeia server using the Politeia server's private key.

**Comment by s-ben** [comment]
The definition above was verified for the `ballot.journal` file. While we're at it though, the `comments.journal` file is also missing definitions for the `signature` and `receipt` fields. Presuming the definitions are similar, have taken a stab below. @lukebp , any chance you can verify this one too? 

**comments.journal**

**Signature:** signature of the comment, which is created using the commenter's private key. This can be used to verify the proposal (or comment on a proposal) that was commented on, the public key of the commenter, and the content of the comment.

**Receipt:** The Politeia server signature of the comment signature. This can be used to verify that the comment was signed (verified) by the Politeia server using the Politeia server's private key.

**Comment by lukebp** [comment]
> Signature: signature of the comment

This is actually the signature of the ProposalToken+ParentCommentID+Comment.

Everything else LGTM.
