### ISSUE TITLE
Discuss the use of Agenda Voting

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrdocs#706]
On the page https://docs.decred.org/governance/introduction-to-decred-governance/ we use the term "Agenda Voting" to refer to Consensus Rules Voting

>Agenda voting to approve or reject a proposed change to the consensus rules of the protocol. A proposed change must be approved by 75% of non-abstaining tickets to take effect.

We should discuss whether we keep using "Agenda" or change it to a more descriptive term.

**Comment by xaur** [comment]
I'm for changing for `Consensus Voting` or `Consensus Rules Voting`. They are more specific and more self-describing. The latter means them more intuitive when used outside of context:

> X: So we have agenda vote going on here  
> Y: Agenda vote?  
> X: Yeah, agendas are changes to consensus rules

**Comment by zubairzia0** [comment]
`Consensus Rules Voting ` is more descriptive than `Agenda Voting` IMO, it is also the title of the section under governance. `Consensus Voting` is still in the vague territory, although it is a bit shorter...

**Comment by jholdstock** [comment]
We actually removed all references to Agenda voting before this issue was created - the one example linked by Noah was just a link which was not updated. Created a PR to fix.
