### ISSUE TITLE
Inflation page: Why 60/30/10 split?

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#707]
https://docs.decred.org/advanced/inflation/

We explain that the block reward is split 60/30/10, but not why it is split that way.

We can mention that PoW reward being bigger than PoS reward prevents rich getting richer - early adopters and whales are constantly diluted by PoW. Also PoW miners face real costs (electricity etc).

**Comment by zubairzia0** [comment]
I think it would help. If the split was closer to 50% then mining would have less incentive than staking, just because of energy expenditure. This would be an unfair advantage for users who stake.
