### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrdocs#73]
As mentioned in the design PR #53, I very much prefer the older dark themed site to the new site with lots of white background on it.  I think we should either go back to lighter text on a dark background for the main body of the text or at least have it as an option.

**Comment by gozart1** [comment]
I'll take a crack at this

**Comment by gozart1** [comment]
Did some initial explorations and came up w/ this:

<img width="1117" alt="dark-theme-explorations" src="https://cloud.githubusercontent.com/assets/25571523/23101108/077102f0-f642-11e6-8069-eea6e76e91e7.png">

LMK what you think and I'll keep going ( next steps would be to rework the search a bit to make it all fit together )

**Comment by jcvernaleo** [comment]
Not sure what anyone else things, but I like that a lot.

**Comment by gratefulcheddar** [comment]
I like it too! It also gets rid of the page display issues I was experiencing with the navigation menu taking up the entire screen due to my window width:
![screen shot 2017-02-22 at 2 03 18 pm](https://cloud.githubusercontent.com/assets/12915233/23229950/ca88da7a-f907-11e6-993d-be9ff5b03a61.png)

**Comment by gozart1** [comment]
thx, just FYI I've made a PR for this #81. 
There's a link to a preview build there as well.
I'm planning to do another pass of refinements so lmk anything that could be improved in the comments there please.

**Comment by jcvernaleo** [comment]
I'm closing this (I am the one who requested it in the first place) since we hope to give the overall theme more thought in the near future.
