### ISSUE TITLE
Outdated stakepool logo

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#740]
Unexpected consequence of updating terminology "Stakepool" to "Voting Service Provider". The logo we use for Stakepool in many places is an inflatable pool ring: https://docs.decred.org/img/dcr-icons/Pool.svg
This logo doesn't make much sense with the new name VSP

**Comment by s-ben** [comment]
Can implement this. Though maybe Governance icon is better? It emphasizes that VSPs (and ticketholders) are active participants in Decred's governance.
https://docs.decred.org/img/dcr-icons/Governance.svg
