### ISSUE TITLE
Change the URL for the PoS and PoW pages

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrdocs#745]
In the new docs structure, both PoS Voting and PoW Mining have their own section.

However, their URLs still looks like this: 
https://docs.decred.org/mining/proof-of-stake/
https://docs.decred.org/mining/proof-of-work/

We should remove /mining from the URL.

**Comment by s-ben** [comment]
@jholdstock , do you want to add this to your URL redirect project, or shall I take this one on?

**Comment by jholdstock** [comment]
This will be done in #659
