### ISSUE TITLE
Create 'Proposal Lifecycle' page

### ISSUE THREAD

**Issue by s-ben** [decred/dcrdocs#753]
In the [Politeia Proposals and Voting page](https://docs.decred.org/governance/politeia/), we give a high-level overview of the process of the proposal lifecycle. However, it was created before Pi launched, and could use an update incorporating what we've learned from the first batches of proposals. In addition, this would make our only existing page on Pi less unwieldy, and make it a better "landing page" for the new /Politeia submenu I'm proposing in another Issue.

**Comment by xaur** [comment]
I'd also link to prpoposal guidelines and add a short note that good proposals' lifecycle begins before it is submitted to Politeia.

**Comment by s-ben** [comment]
I was thinking this would make a good separate page, but once I updated the main politeia page, I realized the high-level lifecycle content fit better in the general description of Politeia. Open to debate though.
