### ISSUE TITLE
Improve transaction details page

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#760]
Mentioned by dave on slack

> I noticed in support last night that https://docs.decred.org/advanced/transaction-details/ is slightly out of date
> 
> For one, the serialization formats at the bottom need to remove 3 and 4
> https://github.com/decred/dcrd/blob/master/wire/msgtx.go#L136-L151
> 
> Those should've never been included in there as they have to do with the signature hash, not wire serialization
> 
> Also, it doesn't call out how the version is treated as a version and the serialization type
> 
> I would also highly suggest showing an example encode/decode, like https://docs.decred.org/advanced/block-header-specifications/

**Comment by s-ben** [comment]
Working on this...
