### ISSUE TITLE
Help Windows and non-CLI users to verify signatures

### ISSUE THREAD

**Issue by xaur** [decred/dcrdocs#771]
It is not easy to verify hashes and signatures on Windows and few people do it. Extend the [Verifying Binaries](https://docs.decred.org/advanced/verifying-binaries/) page (or add subpages) to help a wider spectrum of users.

See [this](https://matrix.to/#/!MgQoetFiyjrHAywokv:decred.org/$15466146857608MMGEy:decred.org) discussion for multiple ideas of things that can be noted on the page, including:

* on Windows using PowerShell: `get-filehash -algorithm sha256 <file>`, PowerShell must be enabled in Control Panel and must be at least v4 where the command was introduced 
* if 7zip is installed, it gives context menu option to calculate sha256 hash for any file
* "with Kleopatra GUI for GNUPG and simple tutorial and links for downloading signing keys and asc files i am able to check most binaries" (cc @sambiohazard)
* https://www.gpg4win.org/features.html
* you can check hashes right from the Explorer as of Windows 10.  Right click the file, CRC SHA -> SHA-256.

If third party software is mentioned, also mention it is a risk by itself.

**Comment by jrick** [comment]
macOS as well.

**Comment by xaur** [comment]
If macOS binaries are signed with CA, [this](http://osxdaily.com/2016/03/14/verify-code-sign-apps-mac-os-x/) can help too

**Comment by jholdstock** [comment]
Video produced by Jazzah on this topic: https://www.bitchute.com/video/9798Ku39MjVi/

Also some content is included in the binary releases readme: https://github.com/decred/decred-binaries/blob/v1.4.0/README.md#verifying-binaries
