### ISSUE TITLE
Include ticket voting chart

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#805]
https://github.com/decred/dcrdocs/issues/489#issuecomment-389770863

This comment from @davecgh includes a nice diagram showing the change of a ticket voting over time. I think this would be a nice addition to the docs.

In an ideal world we would not simply include this as an image, but instead include some kind of source file which means that the chart can be easily updated.

**Comment by jholdstock** [comment]
svg is one option. Or something like graphviz we could generate a png/other image file from.

**Comment by xaur** [comment]
Example graph generated with graphviz in dcrd repo: gv source and svg [here](https://github.com/decred/dcrd/tree/master/docs/assets), rendered image in the [README](https://github.com/decred/dcrd/blob/master/docs/README.md).
