### ISSUE TITLE
Diagram showing how addresses are composed

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#806]
In #801 we discussed adding a diagram to the docs which shows how addresses are composed, similar to the following.

In an ideal world we would not simply include this as an image, but instead include some kind of source file which means that the chart can be easily updated. 

![51638521-63c1dd80-1f13-11e9-854b-b459d88db24c](https://user-images.githubusercontent.com/6762864/51676468-94b31880-1fce-11e9-9533-cd246e70f51b.png)

**Comment by s-ben** [comment]
Hey @zubairzia0 , go for it. Was thinking of doing this, but don't have the knowledge to update it.

**Comment by jholdstock** [comment]
Personally I think SVG would be fine, but @xaur expressed concerns with browser compatibility. There is a possibility that SVG files can be used maliciously because they are interpreted by the browser.  There is a potential to embed malicious code inside them, and as a result, some security focused browsers may not render them.

As this would only affect a very small set of users (who are probably used to a non-standard browsing experience anyway), and because this graphic would not be an integral part of the reading experience, and considering the convenience for making updates to the diagram in the future, I believe this risk to be acceptable.

**Comment by xaur** [comment]
For reference, sanitization of SVG files was discussed in decred/politeia#607 and in the [comment](https://github.com/decred/politeia/issues/607#issuecomment-459865488) I linked to chat discussions.

@degeri can subresource integrity be used to pin hashes of SVG files?

**Comment by degeri** [comment]
Hi SVG files are only an issue if it is supplied by the users. If it is only us creating and updating the file then there is no issue.

**Comment by xaur** [comment]
@degeri sure, I mean can SRI be used as an extra bit of protection against MITM, where _our_  HTML page 'locks in' hashes of _our_ SVGs so they can't be swapped? Or am I overthinking this?

**Comment by degeri** [comment]
I have only seen it being used for CSS and JavaScript and specs don't seem to mention anything else.

But I did find this https://github.com/ShopupStore/IntegrityChecker/blob/master/README.md

**Comment by zubairzia0** [comment]
so no special vector graphics skills here, I was planning to use Inkspcape. Looks like the SVG output is pretty clean when its made in Inkscape so updating wouldent be a problem. Here is an example I made, what do you guys think ? I put in a fingerprint image with a creative commons licence, not sure if it adds value.

![p2pkh generation process](https://user-images.githubusercontent.com/23157945/52184899-4fb98e00-27e7-11e9-9cd9-de655b230d5f.png)

**Comment by s-ben** [comment]
Graphics look good @zubairzia0. Can anyone on this thread review the technical accuracy? The thumbprint I would leave out. My first impression was, "we use biometrics??".

**Comment by zubairzia0** [comment]
lol it definitely seems like that, will remove the fingerprint

**Comment by zubairzia0** [comment]
Another version

![image](https://user-images.githubusercontent.com/23157945/52192945-9a083280-281a-11e9-8c6e-936a845328c2.png)

**Comment by s-ben** [comment]
If you mean a real example public key, not what you have above, I believe the policy is that we don't use real public keys for security reasons. However, you could generate a testnet address not related to other projects if you wanted something more realistic looking.

**Comment by zubairzia0** [comment]
Version with examples posted by @davecgh on DCR support channel. Can put a note that the address and keys are examples.
![image](https://user-images.githubusercontent.com/23157945/52312012-00a26300-2977-11e9-98e3-42adc53c4c5d.png)

**Comment by davecgh** [comment]
Glad to see that converted!

I would say it's not very clear what the checksum is comprised of in that diagram.  I obviously already know since this is based on information I posted, but looking at it as if I didn't already know, it would not be clear to me.

Next, I would also drop `Hash256` in favor of `BLAKE256`.   e.g. `Hash256(BLAKE256)` => ` BLAKE256(Compressed Public Key)`  Same for the other instance.

Finally, the mention of ` Base256`  there is not accurate.  It should be `Base58` and the row below it removed.

**Comment by zubairzia0** [comment]
Made the approptiate changes. How does this look?

![image](https://user-images.githubusercontent.com/23157945/52328070-58af8880-29bc-11e9-9825-0e85bfd2fd47.png)

**Comment by davecgh** [comment]
That looks accurate to me.  The only other thing I might suggest is to keep the words vs variable names consistent.

For example, the top box says `Public key (compressed)` while the next one refers to it as `compressed public key`.  Then, the `ripemd160 preimage`, `checksum preimage`, and `base58 preimage` use camel-cased variable names.

**Comment by zubairzia0** [comment]
yes, I had that in my mind but went against it for some reason. I have updated the above image to make it consistent.
