### ISSUE TITLE
No way to link to category

### ISSUE THREAD

**Issue by xaur** [decred/dcrdocs#814]
Someone [asked](https://www.reddit.com/r/decred/comments/ajpi3s/voting_service_providers_tech_questions/) a question about where to start and I wanted to share one "root" link for PoS that would overview and link to all "nested" pages. While there is a "Proof of Stake" item in the sidebar tree, there is no page corresponding to it, only nested pages. i.e. there's no

https://docs.decred.org/proof-of-stake/

I also wanted to link to "the FAQs" but again there's no page for "PoS FAQ", i.e. here:

https://docs.decred.org/faq/proof-of-stake/

**Comment by xaur** [comment]
Agreed FAQ placement is confusing. For example, why Wallets and Seeds FAQ page is not under Wallets?

**Comment by jholdstock** [comment]
Agreed - all FAQ pages should come under the single FAQ top-level menu. I've opened https://github.com/decred/dcrdocs/issues/833 for that.

Correct @s-ben - there is no way at the moment to host a page at a top-level menu item. Looking at the [mkdocs documentation](https://www.mkdocs.org/user-guide/writing-your-docs/): 

> Note that a section cannot have a page assigned to it. Sections are only containers for child pages and sub-sections.

There may be plugins for mkdocs which make this possible but I've not investigated.

**Comment by xaur** [comment]
> Note that a section cannot have a page assigned to it. Sections are only containers for child pages and sub-sections.

Sigh. So no easy single "entry point" pages for topics.

A possible workaround is to use first page in the section and call it e.g. Overview. The function of such Overview is to serve as a single entry point for the topic and guide through other pages in that section. So when someone asks "How PoS works?" I can drop them just one link.

[Introduction to Decred Governance](https://docs.decred.org/governance/introduction-to-decred-governance/) has some spirit of entry points idea, although it doesn't fully link to all other pages in the Governance section.

**Comment by xaur** [comment]
Blocknet also uses MkDocs and they have these 'entry point' pages called Introduction in several sections, e.g. https://docs.blocknet.co/governance/introduction/

**Comment by s-ben** [comment]
@xaur, I see the 'Introduction' pages, but when I click on the top-level menus, it still just opens the menu, doesn't go to a page.

**Comment by xaur** [comment]
@s-ben yes because they also use MkDocs. That link is interesting because it is a live example of Overview/Introduction pages discussed as a workaround to MkDocs not letting to have pages for top level menus.

**Comment by s-ben** [comment]
@xaur  ah I see. It looks pretty much like what we have already though. For instance, our governance intoduction page is similar.
https://docs.decred.org/governance/introduction-to-decred-governance/

We just call it 'Introduction to Decred Governance' in the menu instead of just 'Introduction'. They have also standardized on having pages titled 'Introduction' for major top-level menus, whereas we have 'Introduction', 'Overview' and 'General' pages that are pretty much the same idea (introducing a subject). We could at least standardize on a naming convention for these pages. 'Introduction' and 'Overview' both work IMO.

**Comment by noahpierau** [comment]
Agreed that the creation of "entry point" pages (with a standard name format) will be a big step forward.

We should strive for intro pages that give high level explanations of the topic, with links to relevant details on other pages.

This will also solve the "double URL" issue:
docs.decred.org/topic/introduction
instead of docs.decred.org/topic/topic

**Comment by jholdstock** [comment]
The above PR is in production now. It renames existing entry-point/introduction pages to "Overview".

Are there any extra sections which require Overview pages? Or could this issue be closed?

**Comment by xaur** [comment]
I walked the nav tree and it looks great and more consistent!

How about these two as well:

https://docs.decred.org/governance/introduction-to-decred-governance/
https://docs.decred.org/contributing/contributing-to-decred/

Their titles look good on the page, but in the sidebar and URL path it could be Overview (like done [here](https://docs.decred.org/governance/politeia/overview/). What do you think?

**Comment by s-ben** [comment]
Both of these pages look better with 'Overview' as the menu title. This would also make our use of 'Overview' standard across all categories that make sense. Have created a PR implementing this: #914. This PR automatically closes this Issue also, as I think we've come as far as we can on this without the ability to directly link to menus (not feasible in MkDocs right now). Speak now or forever hold your peace.

**Comment by noahpierau** [comment]
The old pages now show `404 - Not found`. Can we redirect them to the overview page?

Examples:
- https://docs.decred.org/proof-of-stake/proof-of-stake/
- https://docs.decred.org/governance/politeia/politeia/
