### ISSUE TITLE
Content spoofing

### ISSUE THREAD

**Issue by lemonkabir** [decred/dcrdocs#818]
Hey There have content spoofing issue.Please fix it.For identifying please check my enclosed attachments. 1st for request

1st request
![image](https://user-images.githubusercontent.com/40144795/51864208-48206200-236d-11e9-928a-8102f6ba01fd.png)

2nd response

![image](https://user-images.githubusercontent.com/40144795/51864234-54a4ba80-236d-11e9-81dc-4770bead639a.png)

Thanks

**Comment by jholdstock** [comment]
Thanks.

Resolved by #820
