### ISSUE TITLE
CSS: Centering images?

### ISSUE THREAD

**Issue by gratefulcheddar** [decred/dcrdocs#82]
Anyone disapprove of the centering of images? I don't think it's possible to do this via markdown syntax but I know that we can use raw HTML/CSS to insert images in the docs. Can we add a centered img class to the base.css file? Would have to have these properties:

```
img.centered {
    display: block;
    margin-left: auto;
    margin-right: auto;
}
```

**Comment by jholdstock** [comment]
@jolan @dajohi - I suggest we close this - it's very old and was raised against the previous theme

**Comment by jolan** [comment]
Addressed by new design/theme.
