### ISSUE TITLE
Illustrated ticket splitting guide

### ISSUE THREAD

**Issue by RichardRed0x** [decred/dcrdocs#826]
Following [discussion](https://matrix.to/#/!tfqymymiNgzSUJTHqS:decred.org/$154932296728740mjiny:decred.org?via=decred.org&via=matrix.org&via=zettaport.com) of a [video](https://www.youtube.com/watch?v=9L8P7hL5v6w) about ticketsplitting, it was suggested that maybe this would be a good time to add a more in depth ticket splitting guide (with pictures) on docs.

**Comment by s-ben** [comment]
Could take this on.

**Comment by RichardRed0x** [comment]
Sounds good

**Comment by s-ben** [comment]
Close? Forgot to auto close this Issue, but the [PR](https://github.com/decred/dcrdocs/pull/875) implementing this was merged.

**Comment by matthawkins90** [comment]
@jholdstock, I think this issue should be closed. The guide is posted, and appears to be relatively up-to-date. If further updates are needed, can that be handled in a new issue?

**Comment by jholdstock** [comment]
Thanks Matt
