### ISSUE TITLE
Update proposal example to include proposal summary

### ISSUE THREAD

**Issue by camus-code** [decred/dcrdocs#828]
Once https://github.com/decred/politeiagui/pull/1010 is in, proposals will now include a summary section included by the author upon submission. 

The docs should be updated to reflect that, including the Proposal Guidelines section along with the example proposal section.

**Comment by s-ben** [comment]
On it

**Comment by camus-code** [comment]
Proposal summary will no longer be implemented. Closing this issue @s-ben
