### ISSUE TITLE
Move How to Vote under Consensus Rule Changes

### ISSUE THREAD

**Issue by xaur** [decred/dcrdocs#839]
[How to Vote on consensus rule changes](https://docs.decred.org/governance/how-to-vote/) already links to [Voting Preparation](https://docs.decred.org/governance/consensus-rule-voting/consensus-rules-voting/#voting-preparation) under Consensus Rule Changes. It makes sense to move How to Vote there too.

**Comment by s-ben** [comment]
This makes sense. Glad to see us doing a little reorg pass. Implemented in PR https://github.com/decred/dcrdocs/pull/842
