### ISSUE TITLE
Search bar eats too much space

### ISSUE THREAD

**Issue by xaur** [decred/dcrdocs#84]
Search bar is huge. Seriously. The layout looked just fine in the default theme ([example](http://docs.electrum.org/en/latest/)).

**Comment by jholdstock** [comment]
Does anyone else see this issue or have a method to recreate this?

I have tested in Chrome on desktop and mobile and it appears nicely in both. 

Mobile:
![screenshot_20170317-162246](https://cloud.githubusercontent.com/assets/6762864/24052632/1720cb3a-0b2e-11e7-820a-8b73d45936df.png)

Desktop:
![search-docs](https://cloud.githubusercontent.com/assets/6762864/24052465/80cfadc2-0b2d-11e7-96c8-3ba44cb7025c.jpg)

**Comment by jcvernaleo** [comment]
I tried on a few browsers (mobile and desktop) and I cannot see a problem.  I'll leave this open a little longer in case someone ( @xaur maybe) can provide an example or screenshot.  Otherwise I'll close it next time I go through the Issues.

**Comment by xaur** [comment]
Seems it was fixed couple weeks ago. I'm enjoying proper layout now. Thanks!

Not sure if I'm allowed to close issues, so please close this one.

**Comment by jcvernaleo** [comment]
Great, thanks for following up!  Closing it now.
