### ISSUE TITLE
Verifying proposal censorship

### ISSUE THREAD

**Issue by xaur** [decred/dcrdocs#847]
A short copy was [added](https://github.com/decred/politeiagui/pull/944) to politeiagui that explains how to verify proposal censorship. Later the onboard modal was [removed](https://github.com/decred/politeiagui/pull/986). Check that these verification steps are somewhere in the docs, and if not, add them.

I don't remember that these steps are anywhere in the docs, but if so, apologies for false positive.

**Comment by s-ben** [comment]
They weren't in the docs before, but IMO we should definitely add this now that we have the Politeia section. We could put these steps on the Politeia page under the [Transparent Censorship](https://docs.decred.org/governance/politeia/politeia/#transparent-censorship) section. Alternately, we could create a separate page page, maybe 'Proving Censorship'. This wouldn't be a big page, and the steps could easily fit in the Politiea page, but I kinda like the statement of having a separate page. Thoughts? Below is the text on verifying censorship that I grabbed from the PR above that added it,

 **How to Verify Proposal Censorshsip:**
 1. Navigate to the page of the proposal in question.
2. Click on _Download Proposal Bundle_.
3. Open the downloaded file in an application which can read JSON files.
4. Verify the number in the 'status' row. A censored proposal will have a status code of 3.        
_Note: All proposal status codes can be viewed
[on Github](https://github.com/decred/politeia/tree/master/politeiawww/cmd/politeiawwwcli#proposal-status-codes)_

**Comment by xaur** [comment]
"How to" sounds different from the "theory" style of Politeia page. I would even consider this for Proposal Guidelines - they guide "how to" submit a proposal, can do same for proving censorship.

A bit related question: can redirects be configured for anchors? e.g. can we later redirect

`https://docs.decred.org/governance/politeia/politeia/#proving-censorship` to its own page?

**Comment by s-ben** [comment]
Hmm...The Proposal Guidelines page seems more about creating and submitting proposals. I don't imagine someone would naturally look there for information about proving censorship of a proposal. It could go there though too. I don't think there's an obvious place for it. Other than perhaps in its own page, but that maybe gives it too much importance. It's not much content, and could be fit into the Proposal Guidelines or Politeia page just as easily. 

re: redirecting anchors, I just googled around for a couple minutes, and it appears that redirects only happen at the page level. If we send the server,
`https://docs.decred.org/governance/politeia/politeia/#proving-censorship`
it only sees,
`https://docs.decred.org/governance/politeia/politeia/`

I see some people posting workarounds with Javascript and other tricks, but don't know if we want to mess with that, do we @jholdstock ?

**Comment by RichardRed0x** [comment]
I agree that this probably warrants its own page.

**Comment by xaur** [comment]
> The Proposal Guidelines page seems more about creating and submitting proposals. I don't imagine someone would naturally look there for information about proving censorship of a proposal.

Looking at order of events in the lifecycle, it is `learn > pre-proposal > submit proposal > a) published | b) censored`.

So if not embedding it in the guidelines, they should at least note it in a logical position and link to a relevant page.

Agreed re minimize the usage of anchors.

**Comment by s-ben** [comment]
Take a stab at this. Per @RichardRed0x 's comment on the PR that added the original instructions to pi (https://github.com/decred/politeiagui/pull/944), I agree we need to show how to cryptographically verify that a proposal was censored, in addition to just checking for the status in the Download Proposal Bundle JSON. There is apparently a command-line tool, [politeia verify](https://github.com/decred/politeia/tree/master/politeiad/cmd/politeia_verify), for checking if a proposal has been censored. Going to give that a try on testnet.

**Comment by RichardRed0x** [comment]
When you have a solid draft of these instructions I would be happy to field test them.

Here is some short copy notes you can use for the "why" of transparent censorship, as asked for in proposals channel :
Censorship is a necessary tool for administrators of the Politeia platform, who have responsibility for ensuring that it does not host illegal content. Furthermore, with the fee to submit a proposal set at a low level like 0.1 DCR there is a risk that the system could be flooded with spam proposals that waste the time and attention of stakeholders.

Politeia has been designed to provide safeguards against the abuse of censorship by making the use of censorship accountable and transparent. A limitation observed with platforms like reddit is that moderators can censor content silently, leading to the possibility that content can be censored if it goes against the preferred narrative of the moderators. While it is common for users of certain subreddits to complain that they have been censored for posting certain content, they have no way to demonstrate that the content which they claim was censored ever existed. This results in a situation where any dispute is a case of the users' word against that of the moderators'.

Politeia gives users the capacity to demonstrate that they submitted a particular proposal. If the proposal is censored the submitter can prove that this occurred, and so it is not possible for administrators to censor proposals silently.

**Comment by s-ben** [comment]
Thx @RichardRed0x, used most of this in my first draft: https://github.com/decred/dcrdocs/pull/864
