### ISSUE TITLE
Forum link for Operating a VSP

### ISSUE THREAD

**Issue by xaur** [decred/dcrdocs#850]
Someone linked to this forum thread: https://forum.decred.org/threads/hosting-stake-pools.1321/

See if it has any valuable information to include on Operating a VSP page, or at least whether it is useful to link to it from the page.

**Comment by jholdstock** [comment]
I went through the forum quite comprehensively whilst making the page, and I did go through this thread (amongst a few others).

Is there anything in particular from that thread that you think is missing from the docs page?

**Comment by xaur** [comment]
Nothing particular, I just saw it for the first time and thought I'd check. Closing.
