### ISSUE TITLE
theme update

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#870]
material 4.0.2 is out: https://squidfunk.github.io/mkdocs-material/release-notes/#402-_-march-1-2019

**Comment by s-ben** [comment]
I was going to attempt an update, but presumably you or @dajohi needs to do this on the server where we host mkdocs?

**Comment by jholdstock** [comment]
Nope - this can just be done by anybody. The change is made here https://github.com/decred/dcrdocs/blob/master/requirements.txt#L2

Be sure to check the release notes to see if we need to change any of our code, and make sure you build with the new version and test locally to ensure nothing is broken. Just checking the main features should be sufficient 
- does the nav menu still look correct
- does the search still work
- do images and icons still appear
- do mathjax formula still work (see `research/elliptic-curve-signature-algorithms.md`)
- etc

Next time dhill does a deployment, he will rebuild the docker container and it will automatically pick up the new version.

**Comment by s-ben** [comment]
Ah, good to know. Attempting...

**Comment by s-ben** [comment]
Looks good locally. Opened PR: https://github.com/decred/dcrdocs/pull/872
