### ISSUE TITLE
Add license requirements for Pi proposals

### ISSUE THREAD

**Issue by s-ben** [decred/dcrdocs#873]
Per this [discussion](https://matrix.to/#/!lbzTjhzNbIaDbuAxkS:decred.org/$155227389122248OrQwy:decred.org?via=decred.org&via=matrix.org) about a past successful Politeia proposal, all Pi proposals should state clearly whether they are open source, closed source, or have any other restrictions.

**Comment by xaur** [comment]
I suggest extending this issue a bit to add this to the guidelines:

Explicitly and clearly/visibly state:

* total budget
* duration of contract
* license or any other restriction of deliverables (open/closed source, etc)

**Comment by s-ben** [comment]
Agreed. Unless anyone has any additions/objections, will delete this Issue and create a new one that captures all the updates to the proposal guidelines. From what I've seen following discussions in #proposals and other channels, it seems there is consensus on at least these three items.

**Comment by jholdstock** [comment]
As mentioned in #876, if we make changes to our proposal guidelines, we also need to review our own example proposals to ensure they meet those guidelines.

**Comment by xaur** [comment]
@s-ben one benefit to bundle multiple changes to (guidelines + example proposals) is that they can be shared in #proposals for broader review, without spamming that room too much with multiple smaller changes.

**Comment by s-ben** [comment]
@xaur, sounds like a plan. Will take a stab at adding these new basic requirements and will also review our example proposals.

**Comment by xaur** [comment]
If you guys agree to extend the scope of this issue beyond license to "must state clearly" checklist, I suggest to rename the issue to reflect that.

**Comment by s-ben** [comment]
@xaur, I agree the scope of this has broadened to a checklist, and we're not strictly requiring a license in all cases. Since all the comments could be confusing now to new readers if I change the title and description, I would suggest closing this Issue and creating a new one with the full proposed "must state clearly" checklist. xaur, since there are more of your ideas than mine in this now, do you want to create?

**Comment by xaur** [comment]
@s-ben done: #881
