### ISSUE TITLE
Link to github for more detailed RPC command info

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#874]
`dcrctl-rpc-commands.md` contains a brief summary of the available dcrd and dcrwallet RPC commands, however there is more detailed information we can link to on github.

**Comment by s-ben** [comment]
@jholdstock took a stab at this: https://github.com/decred/dcrdocs/pull/882. Surprisingly, I'd not seen this little universe of technical documentation before. Curious to know if I'm pointing to the right places and if there are other opportunities to improve the docs there.
