### ISSUE TITLE
Improving BLAKE-256 Hash Function page

### ISSUE THREAD

**Issue by zubairzia0** [decred/dcrdocs#878]
Looking at the BLAKE-256 hash function page on docs, couldn't help but think that we could bring in some of the information regarding its benefits over SHA-256 and Scrypt.

Blakecoin, not sure if it's still alive, was promoting the benefits of the BLAKE hashing algo back in the day. If we can validate the performance benefits they are advertising on the site it would nicely fit in the (https://docs.decred.org/research/blake-256-hash-function/) section on the docs.

Blakecoin sources:
https://blakecoin.org/about-blakecoin/
https://blakecoin.org/Blakecoin_Introduction.pdf
https://131002.net/blake/

**Comment by jrick** [comment]
I don't think the blakecoin references are useful:

* Merge mining is of no interest
* Blakecoin is designed around 8-round blake256, not 14-route blake256 as decred uses
* All described hashrates (which are already invalid wrt decred per above) are gpu-specific
