### ISSUE TITLE
Proposal guidelines: reporting

### ISSUE THREAD

**Issue by xaur** [decred/dcrdocs#880]
I suggest to include an important missing recommendation: reporting.

Recommend proposal authors to state their reporting commitment. What will be their reporting schedule and volume, where to follow, and who will be responsible.

This recommendation might need some discussion in #proposals and may trigger some controversy, but I believe this very important for anything that is paid from the Treasury.

Perhaps reporting commitment belongs to ["must state this clearly"](https://github.com/decred/dcrdocs/issues/873#issuecomment-471791429) checklist, but posting it as a separate issue for now. If that turns to be inconvenient, can merge into issue #873 or other.

**Comment by jholdstock** [comment]
Implemented in #896
