### ISSUE TITLE
Update link to dcrd json rpc api doc

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#883]
decred/dcrd#1687 moves `json_rpc_api.md` to `json_rpc_api.mediawiki`.

If/when this is merged, we need to update `dcrctl-rpc-commands.md` to point to the new location

**Comment by s-ben** [comment]
Will keep my eye on this (and Travis yelling when this breaks the build).

**Comment by jholdstock** [comment]
It wont actually break the build because this is considered an external link to github.com. The build only checks internal links which stay within docs.decred.org
