### ISSUE TITLE
Review glossary definition of RCI and SVI

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#889]
> #### Rule Change Interval (RCI)
> 
> An interval of 8064 blocks (~4 weeks) in which ticket holders can vote on consensus rule changes. A Rule Change Interval (RCI) consists of four Stake Version Intervals (SVI), which are 2016 blocks (~1 week). Once the conditions for a vote have been met during an SVI, voting is scheduled to begin on the first block of the next RCI. Because there are four SVIs per RCI, it can take up to 6048 blocks [3 SVIs] for the next RCI to begin.

Also RCIs are not necessarily made up of 4 SVIs. On testnet one RCI is 2.5 SVIs.

**Comment by s-ben** [comment]
Are RCIs on mainnet always made up of 4 SVIs? As a quick fix, we could just say "A Rule Change Interval (RCI) **on mainnet** consists of four Stake Version Intervals (SVI)" 

Not sure where in dcrdocs it makes sense currently to specify that the testnet uses 2.5 SVIs...Presumably testnet specs are in GitHub documentation somewhere?

**Comment by jholdstock** [comment]
The rules don't actually specify a 4:1 relationship or a 2.5:1 relationship. The rules simplify specify the length of the RCI and the SVI:

```
Mainnet:
	RCI: 8064 blocks
	SVI: 2016 blocks

Testnet:
	RCI: 5040 blocks
	SVI: 2016 blocks
```

I don't think it actually makes a lot of sense to mention the 4:1 ratio at all. I will have a go and re-writing this now.

_Full disclosure: I wrote the initial text myself, when I wasn't actually aware of the above_ :stuck_out_tongue:
