### ISSUE TITLE
fa icons are missing

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#891]
Somewhere along the line we seem to have lost font-awesome icons in the docs.

For example, a `fa-book` icon should be shown before the `References` heading on this page: https://docs.decred.org/research/elliptic-curve-signature-algorithms/

**Comment by s-ben** [comment]
@jholdstock started looking into this, but realized there was some history here:
https://github.com/decred/dcrdocs/pull/474
https://github.com/decred/dcrdocs/pull/50

Before I go further down this rabbit hole, are there any issues/restrictions you know of?

It appears we could just update to the latest version of font-awesome, but don't want to introduce breaking changes or do a bunch of manual work if it's avoidable.

**Comment by jholdstock** [comment]
It seems that the fa support was broken on this commit: https://github.com/decred/dcrdocs/commit/d6b683401ade152da9410c4eaa97b0635ff9a9ee

I assume it is something to do with my changes to `mkdocs.yml`, I cant imagine its related to changes in `.md` files

**Comment by jholdstock** [comment]
Oops. I was clumsy when I moved those fields and didn't realise that they werent the only ones under the `extras:` section. The PR above fixes it
