### ISSUE TITLE
Add more detail to the governance introduction

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrdocs#912]
Right now, it says on-chain governance servers 2 purposes:

1. Consensus voting
2. Voting to approve the work of PoW Miners. In order for a PoW Miner to receive their share of the block reward, at least three of the five tickets called in the subsequent block must approve their block. This gives ticket-holders power over PoW Miners in the case of undesirable behavior by miners (e.g. mining empty blocks), although this power is yet to be exercised on mainnet.

While the second part is technically true, it doesn't capture the full nuance. 

Block voting consists of two parts: at least three out of five tickets must vote on a block for the block to be valid, and from those tickets, [at least 50%](https://gist.github.com/jrick/d241c094bbf6c36e0aea9ff36f3d3721) must vote "Yes" to approve the previous block (if less than 50% votes yes, that block will still exist but it will remove the PoW miner reward, the Treasury dividend, and all regular transactions from the previous block). 

These two parts (validation of the block and approval of the previous block) are both important governance mechanisms, and I think they should both be mentioned.

**Comment by RichardRed0x** [comment]
I agree that the intro could be expanded in this way. Or, maybe we should have a whole page about "block voting", I don't think it currently has a lot of description on docs but it's an interesting and important aspect.
