### ISSUE TITLE
Gratefulcheddar requested CSS additions

### ISSUE THREAD

**Issue by karamble** [decred/dcrdocs#92]
.col-md-9 li {
    font-family: 'Source Sans Pro', sans-serif;
    font-size: 1.8rem;
    color: #132f4b;
    font-weight: 600;
}

**Comment by gratefulcheddar** [comment]
This is existing css code. I was wondering if we could remove the high font-weight.

**Comment by gratefulcheddar** [comment]
#99 fixed this.

**Comment by jcvernaleo** [comment]
Missed this one too.  Closing now.
