### ISSUE TITLE
Add random number generator algorithm details

### ISSUE THREAD

**Issue by s-ben** [decred/dcrdocs#941]
In a recent Reddit [post](https://www.reddit.com/r/decred/comments/b8k2i0/where_can_i_read_about_the_pseudo_random_number/), @davecgh answered a question about the pseudo random number generator algorithm used to selects tickets. Dave's description of the algorithm is pretty solid and could probably be dropped into the docs basically as is. I think that if one person had this question, others might as well, and that this information would be good to include somewhere. Thoughts? Does anyone know if this is already documented elsewhere (e.g. a research paper we're already linking to)? Suggestions for a good place to put this?

**Comment by jholdstock** [comment]
another excellent resource for this topic, thanks to @matheusd https://www.youtube.com/watch?v=eysGWVhDFWY

**Comment by s-ben** [comment]
Nice. Video is always good to add. Many people prefer it to text. 

I'm thinking a `Ticket Selection` (or `Ticket Selection Algorithm`) page under /Advanced. Unless this fits better in an existing page (not seeing an obvious place currently).
