### ISSUE TITLE
Improve the governance overview page

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrdocs#944]
To many newcomers, https://docs.decred.org/governance/overview/ is the first impression they will get of Decred's governance system. Since blockchain governance is such a "hot topic", it makes sense to make the most out of this overview page. 

The main suggestion is to add more headers to improve usability (see below). I also think that we need shorter walls of text to make the overview page more attractive for mobile users. This can be achieved by keeping details and exact numbers limited to sub-pages.

The headers could be structured around the different types of voting:

**0 introduction** 
- explain the importance of governance, introduce concept of [voting tickets](https://docs.decred.org/proof-of-stake/overview/#how-ticket-voting-works).

**1 on-chain voting**
- explain what on-chain governance is

**1.1 block voting**
- explain the purpose of block voting
- y/n to approve the regular tx tree of the previous block (if >50% disapproves, it erases the miner reward and treasury budget, and returns the transactions to the mempool)
- abstain to invalidate the current block (when >3 tickets abstain) or else reduce miner reward
- tickets selected per block; tally after each block

**1.2 consensus rule voting**
- explain the purpose of consensus rule voting
- y/n to approve dormant changes to the consensus rules (if >75% approves, the new rules automatically activate)
- abstain to repeat the vote in the next interval (when >90% of eligible tickets abstain)
- tickets selected per block; tally after a rule change interval

**2 off-chain voting** 
- explain what off-chain governance is

**2.1 Politeia voting**
- explain the purpose of Politeia voting
- y/n to approve proposals, either policy changes or funding requests (if >60% approves, they pass)
- abstain to dismiss the proposal (when >80% of eligible tickets abstain)
- tickets selected via snapshot; tally after a week

Each section should keep the text as simple as possible (perhaps the percentage numbers are already too much detail). If readers want to learn more, there will be links to relevant sub-pages.

**Comment by imestin** [comment]
i would like to work on this.
