### ISSUE TITLE
Nav menu scrollbar looks nasty in firefox

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#945]
Chrome:
![Screenshot from 2019-05-18 16-57-22](https://user-images.githubusercontent.com/6762864/57972109-369bae00-798e-11e9-8bd1-db2a7b875f0f.png)

Firefox:
![Screenshot from 2019-05-18 16-58-33](https://user-images.githubusercontent.com/6762864/57972113-3ac7cb80-798e-11e9-9182-94c1ed25547d.png)

**Comment by noahpierau** [comment]
This is how it looks for me:

![image](https://user-images.githubusercontent.com/16287891/57981979-f6e0cf00-7a3e-11e9-9846-90e90ea22341.png)

**Comment by jholdstock** [comment]
Looks like I am seeing the dark one because I am running a dark theme on my OS and firefox is using the default OS style. 

Firefox does not implement custom scrollbars. This can be seen by opening the following in chrome and comparing to opening it in firefox.

https://codepen.io/akinjide/pen/BpggrZ
