### ISSUE TITLE
Add details BLAKE-256 hash function page

### ISSUE THREAD

**Issue by s-ben** [decred/dcrdocs#947]
"Why BLAKE-256?" is a common enough question that @davecgh has written a nice comprehensive answer to this question on [reddit](https://www.reddit.com/r/decred/comments/7rp46d/why_blake256/). This answer could be worked into the [blake-256-hash-function page](https://docs.decred.org/research/blake-256-hash-function/) with minimal editing.

**Comment by zubairzia0** [comment]
Nice find, I was trying to spruce up the blake-256 page in issue 878 but did not find good enough resource nor did I have enough subject matter expertise. This info can definitely be added, I feel, pending @davecgh input.

**Comment by s-ben** [comment]
I got this reddit post from @davecgh when we were chatting about how to reuse technical content from reddit actually. So I think this is a solid resource. Want to take a stab at incorporating?

**Comment by zubairzia0** [comment]
Don't want to take work you have scoped, but if your plate is full I can take a stab.

**Comment by s-ben** [comment]
Left up for a few days in case anyone else wanted it :) Can do myself, but my plate is fulleth right now.

**Comment by zubairzia0** [comment]
Will take it on then

**Comment by zubairzia0** [comment]
This fell through the cracks as June has been a packed month for me. Will be getting to this end of the month.

**Comment by s-ben** [comment]
Some inspiration for you @zubairzia0 :)

![image](https://user-images.githubusercontent.com/1634777/60742314-bd4a2180-9f21-11e9-9dad-61eff0d13c23.png)

**Comment by zubairzia0** [comment]
Haha, saw that and it did inspire me :) . I've worked on the page a bit and had to do alot of background research aswell, should have something by in a few days.

**Comment by zubairzia0** [comment]
Busy week for me. Will be making a push to get a draft out by the weekend.

**Comment by s-ben** [comment]
Hey @zubairzia0, this draft is looking pretty good. Definitely a lot more info that we currently have. Thoughts on just porting some of this to the BLAKE-256 page?

**Comment by zubairzia0** [comment]
Hey @s-ben, have a version locally that is a bit more presentable but I need to put a few hours more hours of work to fix it up.  Getting there slowly but surely.

**Comment by s-ben** [comment]
You're probably aware of this already, but found this nugget on BLAKE-256 in some notes @raedah provided for the dev docs. Thought I'd pass along just in case.

>(from chat on [2019-03-28](https://matrix.to/#/!NNzHoaSdnsbZDQOXJr:decred.org/$155380788346482zglLE:decred.org))

>There is only a single round of blake256 hashing required in Decred versus 2 in sha256 because blake does not have the vulnerabilities that require the double hashing. Then there is the fact that the Decred header provides ample nonce space so it's not necessary to completely recalculate the merkle root every 2^32 nonces (which an ASIC blows through in a few microseconds). The combined result is that it takes much less energy to find a solution for a given hash rate.

**Comment by zubairzia0** [comment]
> You're probably aware of this already, but found this nugget on BLAKE-256 in some notes @raedah provided for the dev docs. Thought I'd pass along just in case.
> 
> > (from chat on [2019-03-28](https://matrix.to/#/!NNzHoaSdnsbZDQOXJr:decred.org/$155380788346482zglLE:decred.org))
> 
> > There is only a single round of blake256 hashing required in Decred versus 2 in sha256 because blake does not have the vulnerabilities that require the double hashing. Then there is the fact that the Decred header provides ample nonce space so it's not necessary to completely recalculate the merkle root every 2^32 nonces (which an ASIC blows through in a few microseconds). The combined result is that it takes much less energy to find a solution for a given hash rate.

I was not sure about that actually, thank you for clearing that up. Now I could include this piece of information. Thank you @s-ben

**Comment by zubairzia0** [comment]
It took a while but finally had more time this month to spend on this and get it done. Please have a look and let me know any feedback.
