### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrdocs#95]
We need to decide on the best way to provide translated docs.

mkdocs does not support anything natively (see https://github.com/mkdocs/mkdocs/issues/617 for details).

That leaves us with a few options.

1. Switch to another doc package.
2. Rearange the current repo so it looks like:
```
dcrdocs/
  en/
  es/
  ru/
  ...
```
Each with a full set of docs.  Then we could serve the default (en) as docs,decred.org and any other language in a subdomain (ru.docs.decred.org) and provide some internal links.  This is more work on the part of the admin.
3. Make a sub dir in the current structure for translations and server those in the same domain as ```docs.decred.org/ru/``` or something like that.
4. Any other ideas I haven't thought of?

**Comment by jcvernaleo** [comment]
Would love comments on this from @dajohi, @jolan, @karamble, @gratefulcheddar, and anyone else interested.

**Comment by karamble** [comment]
I agree. I have researched on the multilanguage issue on mkdocs and couldn't find a reliable solution. My first thought was the same, having multiple directories for the various languages including the full set of docs. We should keep the filenames of the .md files consistent over the language directories so it would be easier to track if the subpages are allready translated. 

We also need a mkdocs.yml for each language. `en_mkdocs.yml` is my suggestion.

Also to make the work for the admin easier we can add a build-the-docs.sh bash script that handles the build process, renaming directories etc. So the admin would just need to point the virtualhosts of the subdomains to the specific language directories.

**Comment by jcvernaleo** [comment]
@karamble so sounds like you are in favor of option 2 above.

Anyone else want to chime in?

**Comment by jolan** [comment]
I've looked at [hugo](https://gohugo.io/) a bit which seems suitable as a mkdocs replacement.  They have a few ways of doing internationalization:

https://gohugo.io/content/multilingual/

I'm not sure it's really worth the effort to switch over since it would require porting the template to be hugo-compatible, having everyone learn golang template syntax, etc.

I am fine with what @karamble proposes.  If we hit snags with that method then we can consider switching.

**Comment by gratefulcheddar** [comment]
I agree with @jolan. Was gonna throw out there Hugo as a suggestion but the work required to switch may not be worth it.

**Comment by dajohi** [comment]
I am fine with option 2.  I strongly support subdirs over subdomains.

**Comment by jcvernaleo** [comment]
This was done in #96
