### ISSUE TITLE
Add section on using dcrtime

### ISSUE THREAD

**Issue by dajohi** [decred/dcrdocs#955]
Add section on using [dcrtime](https://github.com/decred/dcrtime) 

Reason to use
How to use

**Comment by s-ben** [comment]
+1

Surprised we don't have this in the docs already. This [blog](https://blog.decred.org/2017/06/14/Dcrtime/) from when it launched seems to have a good description of the basic architecture and some imagined use cases.

Two current use cases worth mentioning:
* Politeia
* Twitter bot: https://twitter.com/dcrtimestampbot

**Comment by jholdstock** [comment]
Could also mention that dcrtime underpins Voto legal in brazil: https://votolegal.com.br/

**Comment by s-ben** [comment]
Working on this.
