### ISSUE TITLE
v1.4.0

### ISSUE THREAD

**Issue by BigD77** [decred/dcrdocs#956]

**Comment by BigD77** [comment]
Looking for assistance. Old version wasn't syncing so upgraded to 1.4.0 and its stuck syncing SPV wallet for days. Any help would be appreciated!
Darren

**Comment by RichardRed0x** [comment]
Hi Darren, you're not really in the right place for this kind of support. The ideal location would be the support channel on slack, Discord or Matrix, but I think maybe this reddit [post](https://www.reddit.com/r/decred/comments/bnep6p/if_you_were_running_decrediton_at_13_or_earlier/) could be relevant to your predicament.

**Comment by BigD77** [comment]
Ok will check it out thank you

**Comment by jholdstock** [comment]
Not a dcrdocs issue
