### ISSUE TITLE
Add atomic swaps to docs

### ISSUE THREAD

**Issue by s-ben** [decred/dcrdocs#964]
Decred has done considerable work on atomic swaps, and the [decred/atomicswap](https://github.com/decred/atomicswap) repo is under active development. There also exists a considerable amount of technical documentation in the repo README. While I think it makes sense to leave most of the technical documentation on GitHub (where most devs will find it, it's one of our most starred/forked repos), it seems atomic swaps and how they work with Decred specifically, should be represented somewhere in the docs. I would propose a page under /advanced or /research, with the following elements:

- High-level summary of what an atomic swap is
- Basic description of what you can do with Decred's atomic swap tools
- (optional) history of Decred's contribution to atomic swaps
- Pointer to the decred/atomicswaps repo for further technical documentation

**Comment by imestin** [comment]
I would like to do this. I will signal back some days later where I am with it.

**Comment by s-ben** [comment]
Hey @imestin. Sounds good. Was going to take a crack at this myself but don't have time right now. FYI, in case you aren't familiar, the general rule in this repo (@jholdstock correct me if I'm wrong here), is that if someone posts a docs idea as an Issue (as I did with this one), and there are positive comments supporting it, then its up for grabs to work on. Alternatively, if it's been up for a few days and nobody is opposing it (as is the case here), then that generally also means you can start working on it, as long as you give a heads up in the comments that you're working on it (which you have). If you have any questions, feel free to ask here or in chat (e.g. #Documentation channel).

**Comment by imestin** [comment]
Thank you for the information!
I will report on my progress soon.

**Comment by jholdstock** [comment]
This sounds like a good idea to me.

Pretty much correct re. process @s-ben. I typically assume [lazy consensus](http://wiki.eclipse.org/Lazy_Consensus) on low-impact things like documentation. People will usually speak up if they disagree with something, but often remain quiet when they agree.

**Comment by imestin** [comment]
If I think I am ready, should I create pull request or show link to draft first?

**Comment by imestin** [comment]
https://github.com/imestin/dcrdocs/blob/master/docs/advanced/atomic-swap.md

**Comment by jholdstock** [comment]
Create a PR please, and include "Closes #964" somewhere in the description text so GitHub knows to automatically close this issue when the PR is merged

**Comment by imestin** [comment]
ok, I created it.
Thank you!
