### ISSUE TITLE
Add page full node setup

### ISSUE THREAD

**Issue by s-ben** [decred/dcrdocs#987]
Per this [conversation](https://matrix.to/#/!tfqymymiNgzSUJTHqS:decred.org/$156820079627471eFYxw:decred.org?via=decred.org&via=matrix.org&via=zettaport.com), it would be good to have a page with instructions for setting up a full node. @noahpierau has provided the below draft,
https://github.com/noahpierau/articles/blob/master/how-to-run-a-decred-full-node.md

Notes on draft from chat:

jholdstock
>step 7: would be better to put the externalip into the dcrd config file rather than providing it through the flag every time dcrd is started up
>Also you may want to add a note about external ip address needing to remain static. This is quite important for your specific target audience because most household internet connections dont allow this

davecgh
>1.5.0 will no longer need extenalip

Hanon
>yes that's a great improvement! will 1.5.0 automatically detect ip changes as well?

davecgh
>Sort of, but it would take a long time because it keeps a score

Note that 1.5 is an upcoming release.

**Comment by jholdstock** [comment]
Go for it :+1:
