### ISSUE TITLE
Expected vs actual block time

### ISSUE THREAD

**Issue by s-ben** [decred/dcrdocs#993]
Going through @raedah's notes for material to include in the dev docs, saw this snipped on [Block production times](https://github.com/raedahgroup/dcrdevdocs/blob/master/start.md#block-production-times). This is taken from a post @davecgh made to Reddit, in response to being asked a few times regarding this. Worth including in dcrdocs?

**Comment by jholdstock** [comment]
Yep I definitely think we should include this

**Comment by s-ben** [comment]
Cool. Taking a crack at it
