### ISSUE TITLE
FAQ: Can we add 2fa to wallets?

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#997]
A discussion which has happened multiple times on Matrix. [Most recent example](https://matrix.to/#/!wSdymYrEpBhsWlDJuk:decred.org/$15706037277677WgAls:decred.org?via=decred.org&via=matrix.org&via=zettaport.com)

We could capture this as an FAQ on https://docs.decred.org/faq/wallets-and-seeds/

**Comment by RichardRed0x** [comment]
Sounds good, I'm all for FAQ-ing FAQs where there are clear answers. To use chats efficiently any frequently occurring conversation should have a resource that can be linked to.
