### ISSUE TITLE
Update Signature Script Isolation and Fraud Proofs page

### ISSUE THREAD

**Issue by s-ben** [decred/dcrdocs#999]
In the Signature Script Isolation and Fraud Proofs [page](https://docs.decred.org/research/signature-script-isolation-and-fraud-proofs/), we say:

>It is now being proposed for Bitcoin as a soft fork referred to as “Segregated Witness”

This should be updated to say that the soft fork happened. But also wondering if there is other outdated info on this page?

This line also might need updating after [DCP-0005](https://github.com/davecgh/dcps/blob/dcp0005/dcp-0005/dcp-0005.mediawiki#) passes (assuming it does):

>In addition, fraud proofs, as suggested for Bitcoin’s soft fork3, are set by miners and also committed to as part of the data in the merkle tree.

**Comment by imestin** [comment]
I would like to work on this.

**Comment by imestin** [comment]
the [Block Header Specification](https://devdocs.decred.org/developer-guides/block-header-specifications/) also mentions StakeRoot.

**Comment by imestin** [comment]
[Merkle trees in Decred](https://devdocs.decred.org/developer-guides/merkle-root-construction/) also contains information about StakeRoot.
